// Copyright (C) 2026 Texas Instruments Incorporated
//
// SPDX-License-Identifier: Apache-2.0

#include "DSPLIB_addNCh_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
#include "test_data/staticRefCase12.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
#include "test_data/staticRefCase13.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
#include "test_data/staticRefCase14.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
#include "test_data/staticRefCase15.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
#include "test_data/staticRefCase16.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
#include "test_data/staticRefCase17.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
#include "test_data/staticRefCase18.h"
#endif

static DSPLIB_addNCh_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
    {
        STATIC,                                                               // Test pattern
        staticRefIn0Case1,                                                    // Input vector 0
        staticRefOutCase1,                                                    // Output vector
        DSPLIB_FLOAT32,                                                       // precision
        1,                                                                    // Number of input channels in a vector
        1024,                                                                 // Number of samples in a vector
        2,                                                                    // Number of channels in a vector
        DSPLIB_CALC_STRIDE(1024 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                    // number of reps.
        1,                                                                    // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
    {
        STATIC,                                                               // Test pattern
        staticRefIn0Case2,                                                    // Input vector 0
        staticRefOutCase2,                                                    // Output vector
        DSPLIB_FLOAT32,                                                       // precision
        2,                                                                    // Number of input channels in a vector
        1024,                                                                 // Number of samples in a vector
        2,                                                                    // Number of channels in a vector
        DSPLIB_CALC_STRIDE(1024 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                    // number of reps.
        2,                                                                    // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
    {
        STATIC,                                                               // Test pattern
        staticRefIn0Case3,                                                    // Input vector 0
        staticRefOutCase3,                                                    // Output vector
        DSPLIB_FLOAT32,                                                       // precision
        4,                                                                    // Number of input channels in a vector
        1024,                                                                 // Number of samples in a vector
        2,                                                                    // Number of channels in a vector
        DSPLIB_CALC_STRIDE(1024 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                    // number of reps.
        3,                                                                    // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
    {
        STATIC,                                                               // Test pattern
        staticRefIn0Case4,                                                    // Input vector 0
        staticRefOutCase4,                                                    // Output vector
        DSPLIB_FLOAT32,                                                       // precision
        1,                                                                    // Number of input channels in a vector
        2085,                                                                 // Number of samples in a vector
        2,                                                                    // Number of channels in a vector
        DSPLIB_CALC_STRIDE(2085 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                    // number of reps.
        4,                                                                    // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
    {
        STATIC,                                                               // Test pattern
        staticRefIn0Case5,                                                    // Input vector 0
        staticRefOutCase5,                                                    // Output vector
        DSPLIB_FLOAT32,                                                       // precision
        2,                                                                    // Number of input channels in a vector
        2085,                                                                 // Number of samples in a vector
        2,                                                                    // Number of channels in a vector
        DSPLIB_CALC_STRIDE(2085 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                    // number of reps.
        5,                                                                    // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
    {
        STATIC,                                                               // Test pattern
        staticRefIn0Case6,                                                    // Input vector 0
        staticRefOutCase6,                                                    // Output vector
        DSPLIB_FLOAT32,                                                       // precision
        4,                                                                    // Number of input channels in a vector
        2085,                                                                 // Number of samples in a vector
        2,                                                                    // Number of channels in a vector
        DSPLIB_CALC_STRIDE(2085 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                    // number of reps.
        6,                                                                    // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
    {
        STATIC,                                                             // Test pattern
        staticRefIn0Case7,                                                  // Input vector 0
        staticRefOutCase7,                                                  // Output vector
        DSPLIB_FLOAT32,                                                     // precision
        3,                                                                  // Number of input channels in a vector
        10,                                                                 // Number of samples in a vector
        5,                                                                  // Number of channels in a vector
        DSPLIB_CALC_STRIDE(10 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        7,                                                                  // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
    {
        STATIC,                                                              // Test pattern
        staticRefIn0Case8,                                                   // Input vector 0
        staticRefOutCase8,                                                   // Output vector
        DSPLIB_FLOAT64,                                                      // precision
        1,                                                                   // Number of input channels in a vector
        10,                                                                  // Number of samples in a vector
        10,                                                                  // Number of channels in a vector
        DSPLIB_CALC_STRIDE(10 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                             // Output data location
        1,                                                                   // number of reps.
        8,                                                                   // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
    {
        STATIC,                                                              // Test pattern
        staticRefIn0Case9,                                                   // Input vector 0
        staticRefOutCase9,                                                   // Output vector
        DSPLIB_FLOAT64,                                                      // precision
        2,                                                                   // Number of input channels in a vector
        64,                                                                  // Number of samples in a vector
        32,                                                                  // Number of channels in a vector
        DSPLIB_CALC_STRIDE(64 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                             // Output data location
        1,                                                                   // number of reps.
        9,                                                                   // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
    {
        STATIC,                                                            // Test pattern
        staticRefIn0Case10,                                                // Input vector 0
        staticRefOutCase10,                                                // Output vector
        DSPLIB_FLOAT32,                                                    // precision
        2,                                                                 // Number of input channels in a vector
        5,                                                                 // Number of samples in a vector
        2,                                                                 // Number of channels in a vector
        DSPLIB_CALC_STRIDE(5 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                           // Output data location
        1,                                                                 // number of reps.
        10,                                                                // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
    {
        STATIC,                                                             // Test pattern
        staticRefIn0Case11,                                                 // Input vector 0
        staticRefOutCase11,                                                 // Output vector
        DSPLIB_FLOAT32,                                                     // precision
        2,                                                                  // Number of input channels in a vector
        10,                                                                 // Number of samples in a vector
        32,                                                                 // Number of channels in a vector
        DSPLIB_CALC_STRIDE(10 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        11,                                                                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
    {
        STATIC,                                                             // Test pattern
        staticRefIn0Case12,                                                 // Input vector 0
        staticRefOutCase12,                                                 // Output vector
        DSPLIB_FLOAT32,                                                     // precision
        2,                                                                  // Number of input channels in a vector
        64,                                                                 // Number of samples in a vector
        32,                                                                 // Number of channels in a vector
        DSPLIB_CALC_STRIDE(64 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        12,                                                                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
    {
        STATIC,                                                               // Test pattern
        staticRefIn0Case13,                                                   // Input vector 0
        staticRefOutCase13,                                                   // Output vector
        DSPLIB_FLOAT64,                                                       // precision
        12,                                                                   // Number of input channels in a vector
        100,                                                                  // Number of samples in a vector
        16,                                                                   // Number of channels in a vector
        DSPLIB_CALC_STRIDE(100 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                    // number of reps.
        13,                                                                   // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
    {
        STATIC,                                                              // Test pattern
        staticRefIn0Case14,                                                  // Input vector 0
        staticRefOutCase14,                                                  // Output vector
        DSPLIB_FLOAT32,                                                      // precision
        12,                                                                  // Number of input channels in a vector
        128,                                                                 // Number of samples in a vector
        16,                                                                  // Number of channels in a vector
        DSPLIB_CALC_STRIDE(128 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                             // Output data location
        1,                                                                   // number of reps.
        14,                                                                  // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
    {
        STATIC,                                                              // Test pattern
        staticRefIn0Case15,                                                  // Input vector 0
        staticRefOutCase15,                                                  // Output vector
        DSPLIB_FLOAT32,                                                      // precision
        12,                                                                  // Number of input channels in a vector
        256,                                                                 // Number of samples in a vector
        16,                                                                  // Number of channels in a vector
        DSPLIB_CALC_STRIDE(256 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                             // Output data location
        1,                                                                   // number of reps.
        15,                                                                  // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
    {
        STATIC,                                                               // Test pattern
        staticRefIn0Case16,                                                   // Input vector 0
        staticRefOutCase16,                                                   // Output vector
        DSPLIB_FLOAT64,                                                       // precision
        12,                                                                   // Number of input channels in a vector
        128,                                                                  // Number of samples in a vector
        16,                                                                   // Number of channels in a vector
        DSPLIB_CALC_STRIDE(128 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                    // number of reps.
        16,                                                                   // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
    {
        STATIC,                                                              // Test pattern
        staticRefIn0Case17,                                                  // Input vector 0
        staticRefOutCase17,                                                  // Output vector
        DSPLIB_FLOAT32,                                                      // precision
        12,                                                                  // Number of input channels in a vector
        400,                                                                 // Number of samples in a vector
        16,                                                                  // Number of channels in a vector
        DSPLIB_CALC_STRIDE(400 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                             // Output data location
        1,                                                                   // number of reps.
        17,                                                                  // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
    {
        STATIC,                                                              // Test pattern
        staticRefIn0Case18,                                                  // Input vector 0
        staticRefOutCase18,                                                  // Output vector
        DSPLIB_FLOAT32,                                                      // precision
        12,                                                                  // Number of input channels in a vector
        400,                                                                 // Number of samples in a vector
        32,                                                                  // Number of channels in a vector
        DSPLIB_CALC_STRIDE(400 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                             // Output data location
        1,                                                                   // number of reps.
        18,                                                                  // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
    {
        RANDOM,                                                             // Test pattern
        NULL,                                                               // Input vector 0
        NULL,                                                               // Output vector
        DSPLIB_FLOAT32,                                                     // precision
        3,                                                                  // Number of input channels in a vector
        20,                                                                 // Number of samples in a vector
        1,                                                                  // Number of channels in a vector
        DSPLIB_CALC_STRIDE(20 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        19,                                                                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
    {
        RANDOM,                                                              // Test pattern
        NULL,                                                                // Input vector 0
        NULL,                                                                // Output vector
        DSPLIB_FLOAT64,                                                      // precision
        3,                                                                   // Number of input channels in a vector
        20,                                                                  // Number of samples in a vector
        1,                                                                   // Number of channels in a vector
        DSPLIB_CALC_STRIDE(20 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                             // Output data location
        1,                                                                   // number of reps.
        20,                                                                  // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
    {
        RANDOM,                                                             // Test pattern
        NULL,                                                               // Input vector 0
        NULL,                                                               // Output vector
        DSPLIB_FLOAT64,                                                     // precision
        2,                                                                  // Number of input channels in a vector
        5,                                                                  // Number of samples in a vector
        12,                                                                 // Number of channels in a vector
        DSPLIB_CALC_STRIDE(5 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        21,                                                                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
    {
        RANDOM,                                                              // Test pattern
        NULL,                                                                // Input vector 0
        NULL,                                                                // Output vector
        DSPLIB_FLOAT64,                                                      // precision
        2,                                                                   // Number of input channels in a vector
        10,                                                                  // Number of samples in a vector
        32,                                                                  // Number of channels in a vector
        DSPLIB_CALC_STRIDE(10 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                             // Output data location
        1,                                                                   // number of reps.
        22,                                                                  // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
    {
        RANDOM,                                                              // Test pattern
        NULL,                                                                // Input vector 0
        NULL,                                                                // Output vector
        DSPLIB_FLOAT64,                                                      // precision
        2,                                                                   // Number of input channels in a vector
        64,                                                                  // Number of samples in a vector
        32,                                                                  // Number of channels in a vector
        DSPLIB_CALC_STRIDE(64 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                             // Output data location
        1,                                                                   // number of reps.
        23,                                                                  // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
    {
        RANDOM,                                                              // Test pattern
        NULL,                                                                // Input vector 0
        NULL,                                                                // Output vector
        DSPLIB_FLOAT64,                                                      // precision
        8,                                                                   // Number of input channels in a vector
        64,                                                                  // Number of samples in a vector
        16,                                                                  // Number of channels in a vector
        DSPLIB_CALC_STRIDE(64 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                             // Output data location
        1,                                                                   // number of reps.
        24,                                                                  // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 25))
    {
        RANDOM,                                                               // Test pattern
        NULL,                                                                 // Input vector 0
        NULL,                                                                 // Output vector
        DSPLIB_FLOAT32,                                                       // precision
        12,                                                                   // Number of input channels in a vector
        1024,                                                                 // Number of samples in a vector
        1,                                                                    // Number of channels in a vector
        DSPLIB_CALC_STRIDE(1024 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                    // number of reps.
        25,                                                                   // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 26))
    {
        RANDOM,                                                                // Test pattern
        NULL,                                                                  // Input vector 0
        NULL,                                                                  // Output vector
        DSPLIB_FLOAT64,                                                        // precision
        12,                                                                    // Number of input channels in a vector
        1024,                                                                  // Number of samples in a vector
        1,                                                                     // Number of channels in a vector
        DSPLIB_CALC_STRIDE(1024 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                     // number of reps.
        26,                                                                    // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 27))
    {
        RANDOM,                                                              // Test pattern
        NULL,                                                                // Input vector 0
        NULL,                                                                // Output vector
        DSPLIB_FLOAT32,                                                      // precision
        12,                                                                  // Number of input channels in a vector
        512,                                                                 // Number of samples in a vector
        1,                                                                   // Number of channels in a vector
        DSPLIB_CALC_STRIDE(512 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                             // Output data location
        1,                                                                   // number of reps.
        27,                                                                  // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 28))
    {
        RANDOM,                                                               // Test pattern
        NULL,                                                                 // Input vector 0
        NULL,                                                                 // Output vector
        DSPLIB_FLOAT64,                                                       // precision
        12,                                                                   // Number of input channels in a vector
        512,                                                                  // Number of samples in a vector
        1,                                                                    // Number of channels in a vector
        DSPLIB_CALC_STRIDE(512 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                    // number of reps.
        28,                                                                   // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 29))
    {
        RANDOM,                                                                // Test pattern
        NULL,                                                                  // Input vector 0
        NULL,                                                                  // Output vector
        DSPLIB_FLOAT64,                                                        // precision
        4,                                                                     // Number of input channels in a vector
        1024,                                                                  // Number of samples in a vector
        2,                                                                     // Number of channels in a vector
        DSPLIB_CALC_STRIDE(1024 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // strideInElements buffer
        DSPLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                     // number of reps.
        29,                                                                    // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void DSPLIB_addNCh_getTestParams(DSPLIB_addNCh_testParams_t** params, int32_t* numTests)
{
   *params   = testParams;
   *numTests = sizeof(testParams) / sizeof(DSPLIB_addNCh_testParams_t);
}
