# Copyright (C) 2026 Texas Instruments Incorporated
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import print_function
from subprocess import call
from sys import platform

import sys
import numpy as np
import csv

sys.path.append("../common")
import DSPLIB_utils
import file_io

# Import the DSPLIB_matTrans class
from matTrans import DSPLIB_matTrans


def gen_testCaseParams(testParamsFile, currPrm):
    """Generate and write test case parameters to idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    testType = currPrm["testType"]
    dType = currPrm["dType"]
    dimX = int(currPrm["dimX"])
    dimY = int(currPrm["dimY"])
    demoCase = currPrm["demoCase"]
    numReps = currPrm["numReps"]
    outputDataLocation = currPrm["outputDataLocation"]
    testId = currPrm["ID"]

    if testType == "STATIC":
        inputData = "staticRefInCase" + str(testId)
        outputData = "staticRefOutCase" + str(testId)
    else:
        inputData = "NULL"
        outputData = "NULL"

    if demoCase == "true":
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d) || defined(DEMO_CASE))\n"
            % (int(testId))
        )
    else:
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d)|| (TEST_CATEGORY == 100))\n"
            % (int(testId))
        )

    DSPLIB_dataType = DSPLIB_utils.resolve_dType(dType)

    idatFile.write("{\n")
    idatFile.write("%s, // Test pattern \n" % testType)
    idatFile.write("%s, // staticIn \n" % inputData)
    idatFile.write("%s, // staticOut \n" % outputData)
    idatFile.write("%s, // dataType \n" % DSPLIB_dataType)
    idatFile.write("%d, // dimX (width) \n" % dimX)
    idatFile.write("%d, // dimY (height) \n" % dimY)
    idatFile.write(
        "DSPLIB_CALC_STRIDE(%d * sizeof(%s), ALIGN_64BYTES), // strideIn\n"
        % (dimX, dType)
    )
    idatFile.write("%d, // widthOut \n" % dimY)
    idatFile.write("%d, // heightOut \n" % dimX)
    idatFile.write(
        "DSPLIB_CALC_STRIDE(%d * sizeof(%s), OUTPUT_ALIGN_BYTES),// strideOut\n"
        % (dimY, dType)
    )
    idatFile.write("%d, // shift (0 for float/double) \n" % (0))
    idatFile.write("%s, // Output data location \n" % (outputDataLocation))
    idatFile.write("%d, // number of reps. \n" % (int(numReps)))
    idatFile.write("%d, // test ID\n" % int(testId))
    idatFile.write("},\n")
    idatFile.write("#endif")
    idatFile.write("\n\n")


def gen_idat_file(idatFile, testCases):
    """Generate the idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    fIn = open("../common/ti_lice_header_idat.txt", "r")
    lines = fIn.readlines()
    fIn.close()
    idatFile.writelines(lines)
    includeString = '#include "DSPLIB_matTrans_idat.h"'
    idatFile.writelines(includeString)
    idatFile.write("\n")
    idatFile.write("/*This file is autogenerated*/\n")
    idatFile.write("/*Please do not edit*/\n")
    idatFile.write("\n\n")
    idatFile.write("#define ALIGN_64BYTES DSPLIB_ALIGN_SHIFT_64BYTES\n\n")
    idatFile.write("#if defined(__C7504__) || defined(__C7524__)\n")
    idatFile.write("#define OUTPUT_ALIGN_BYTES DSPLIB_ALIGN_SHIFT_64BYTES\n")
    idatFile.write("#else\n")
    idatFile.write("#define OUTPUT_ALIGN_BYTES DSPLIB_ALIGN_SHIFT_128BYTES\n")
    idatFile.write("#endif\n\n")
    # generate ifdefs for header files
    for testCase in testCases:
        if testCase["testType"] == "STATIC":
            DSPLIB_utils.gen_ifdefs(idatFile, testCase)

    # generate parameters for test cases
    idatFile.write("static matTrans_testParams_t testParams[] =  ")
    idatFile.write("{\n")

    for testCase in testCases:
        gen_testCaseParams(idatFile, testCase)

    idatFile.write("};\n\n")
    fIn = open("test_param_function.txt", "r")
    lines = fIn.readlines()

    idatFile.writelines(lines)


def process_test_case(testCase):
    """Convert str to int for necessary parameters

    Args:
        testCase (dict): Dictionary object with test case parameters

    Returns:
        dict: Dictionary object with necessary parameters converted to int
    """
    testCase["numReps"] = int(testCase["numReps"])
    return testCase


def gen_test_case_header_file(testCase):
    """Generate test case and write out input and output matrices
    into a header file usable in C/C++ code.

    Args:
        param1 (:obj: dict): A dict object with all the test case
        parameters

    Returns:
        [int int]: Minimum and maximum value in output matrix

    """

    ##############################
    # Get test parameter of case #
    ##############################

    testId = testCase["ID"]
    dType = testCase["dType"]
    dimX = int(testCase["dimX"])
    dimY = int(testCase["dimY"])

    # Create an instance of the DSPLIB_matTrans class
    matTrans = DSPLIB_matTrans(dataType=dType, dimX=dimX, dimY=dimY)

    # Generate output matrix using the DSPLIB_matTrans class
    outputMatrix = matTrans.exec()

    headerFileName = "staticRefCase" + str(testId) + ".h"
    file_io.write_header_file(
        matTrans.inputMatrix, outputMatrix, testCase, headerFileName
    )

    return [np.min(outputMatrix), np.max(outputMatrix)]


def gen_test_case(testCase):
    if testCase["testType"] == "STATIC":
        [minY, maxY] = gen_test_case_header_file(testCase)
        print(
            "Test case generation completed for test ID",
            testCase["ID"],
            "w/ min:",
            minY,
            "and max",
            maxY,
        )
    else:
        print(
            "Skipping test case generation for test ID",
            testCase["ID"],
            "as tesType is RANDOM",
        )


# CSV file with parameters for all test cases
testCasesCsvFile = "test_cases_list.csv"
testIdList = []  # list of test IDs that we want to generate test data
testIdList += range(1, 322)
# testIdList = [1]

myArgs = DSPLIB_utils.getCmdLineArgs()

#############################################################################
# Open CSV file with test cases and generate header file with test data for #
# test cases of interest; based on testIdList                               #
#############################################################################

with open(testCasesCsvFile, encoding="utf-8-sig") as csv_file:
    testCaseReader = csv.DictReader(csv_file)
    testCases = list(testCaseReader)

    for testCase in testCases:
        testCase = process_test_case(testCase)

    for testCase in testCases:
        if myArgs.allCases or int(testCase["ID"]) in testIdList:
            gen_test_case(testCase)


idatFileName = "../../DSPLIB_matTrans/DSPLIB_matTrans_idat.c"

##########################################################################
# Generate idat.c file by parsing all the test cases in the CSV file   #
##########################################################################

with open(idatFileName, "w") as idatFile:
    gen_idat_file(idatFile, testCases)


if platform == "linux" or platform == "linux2":
    call(["clang-format", "-style=file", "-i", idatFileName])
    call(["indent", "-nut", "-i3", "-c55", "-l200", idatFileName])
    call(["rm", idatFileName + "~"])  # remove backup file


print("Idat file generation completed")
