// Copyright (C) 2026 Texas Instruments Incorporated
//
// SPDX-License-Identifier: Apache-2.0

#include "DSPLIB_svd_small_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
#include "test_data/staticRefCase12.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
#include "test_data/staticRefCase13.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
#include "test_data/staticRefCase14.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
#include "test_data/staticRefCase15.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
#include "test_data/staticRefCase16.h"
#endif

static DSPLIB_svd_small_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
    {
        STATIC,                                                             // Test pattern
        staticRefInCase1,                                                   // Input matrix A
        staticRefOutUCase1,                                                 // Output matrix U
        staticRefOutVCase1,                                                 // Output matrix V
        staticRefOutDiagCase1,                                              // Output array Diag
        DSPLIB_FLOAT64,                                                     // precision
        6,                                                                  // widthIn
        6,                                                                  // heightIn
        DSPLIB_CALC_STRIDE(6 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // stride of A matrix
        0,                                                                  // enableReducedForm
        0,                                                                  // shift
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        1,                                                                  // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
    {
        STATIC,                                                             // Test pattern
        staticRefInCase2,                                                   // Input matrix A
        staticRefOutUCase2,                                                 // Output matrix U
        staticRefOutVCase2,                                                 // Output matrix V
        staticRefOutDiagCase2,                                              // Output array Diag
        DSPLIB_FLOAT64,                                                     // precision
        6,                                                                  // widthIn
        6,                                                                  // heightIn
        DSPLIB_CALC_STRIDE(6 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // stride of A matrix
        1,                                                                  // enableReducedForm
        0,                                                                  // shift
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        2,                                                                  // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
    {
        STATIC,                                                             // Test pattern
        staticRefInCase3,                                                   // Input matrix A
        staticRefOutUCase3,                                                 // Output matrix U
        staticRefOutVCase3,                                                 // Output matrix V
        staticRefOutDiagCase3,                                              // Output array Diag
        DSPLIB_FLOAT64,                                                     // precision
        7,                                                                  // widthIn
        6,                                                                  // heightIn
        DSPLIB_CALC_STRIDE(7 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // stride of A matrix
        0,                                                                  // enableReducedForm
        0,                                                                  // shift
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        3,                                                                  // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
    {
        STATIC,                                                             // Test pattern
        staticRefInCase4,                                                   // Input matrix A
        staticRefOutUCase4,                                                 // Output matrix U
        staticRefOutVCase4,                                                 // Output matrix V
        staticRefOutDiagCase4,                                              // Output array Diag
        DSPLIB_FLOAT64,                                                     // precision
        7,                                                                  // widthIn
        6,                                                                  // heightIn
        DSPLIB_CALC_STRIDE(7 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // stride of A matrix
        1,                                                                  // enableReducedForm
        0,                                                                  // shift
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        4,                                                                  // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
    {
        STATIC,                                                             // Test pattern
        staticRefInCase5,                                                   // Input matrix A
        staticRefOutUCase5,                                                 // Output matrix U
        staticRefOutVCase5,                                                 // Output matrix V
        staticRefOutDiagCase5,                                              // Output array Diag
        DSPLIB_FLOAT64,                                                     // precision
        6,                                                                  // widthIn
        6,                                                                  // heightIn
        DSPLIB_CALC_STRIDE(6 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // stride of A matrix
        0,                                                                  // enableReducedForm
        0,                                                                  // shift
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        5,                                                                  // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
    {
        STATIC,                                                             // Test pattern
        staticRefInCase6,                                                   // Input matrix A
        staticRefOutUCase6,                                                 // Output matrix U
        staticRefOutVCase6,                                                 // Output matrix V
        staticRefOutDiagCase6,                                              // Output array Diag
        DSPLIB_FLOAT64,                                                     // precision
        6,                                                                  // widthIn
        6,                                                                  // heightIn
        DSPLIB_CALC_STRIDE(6 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // stride of A matrix
        1,                                                                  // enableReducedForm
        0,                                                                  // shift
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        6,                                                                  // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
    {
        STATIC,                                                             // Test pattern
        staticRefInCase7,                                                   // Input matrix A
        staticRefOutUCase7,                                                 // Output matrix U
        staticRefOutVCase7,                                                 // Output matrix V
        staticRefOutDiagCase7,                                              // Output array Diag
        DSPLIB_FLOAT64,                                                     // precision
        7,                                                                  // widthIn
        6,                                                                  // heightIn
        DSPLIB_CALC_STRIDE(7 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // stride of A matrix
        0,                                                                  // enableReducedForm
        0,                                                                  // shift
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        7,                                                                  // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
    {
        STATIC,                                                             // Test pattern
        staticRefInCase8,                                                   // Input matrix A
        staticRefOutUCase8,                                                 // Output matrix U
        staticRefOutVCase8,                                                 // Output matrix V
        staticRefOutDiagCase8,                                              // Output array Diag
        DSPLIB_FLOAT64,                                                     // precision
        7,                                                                  // widthIn
        6,                                                                  // heightIn
        DSPLIB_CALC_STRIDE(7 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // stride of A matrix
        1,                                                                  // enableReducedForm
        0,                                                                  // shift
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        8,                                                                  // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
    {
        STATIC,                                                             // Test pattern
        staticRefInCase9,                                                   // Input matrix A
        staticRefOutUCase9,                                                 // Output matrix U
        staticRefOutVCase9,                                                 // Output matrix V
        staticRefOutDiagCase9,                                              // Output array Diag
        DSPLIB_FLOAT64,                                                     // precision
        6,                                                                  // widthIn
        6,                                                                  // heightIn
        DSPLIB_CALC_STRIDE(6 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // stride of A matrix
        0,                                                                  // enableReducedForm
        0,                                                                  // shift
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        9,                                                                  // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
    {
        STATIC,                                                             // Test pattern
        staticRefInCase10,                                                  // Input matrix A
        staticRefOutUCase10,                                                // Output matrix U
        staticRefOutVCase10,                                                // Output matrix V
        staticRefOutDiagCase10,                                             // Output array Diag
        DSPLIB_FLOAT64,                                                     // precision
        6,                                                                  // widthIn
        6,                                                                  // heightIn
        DSPLIB_CALC_STRIDE(6 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // stride of A matrix
        1,                                                                  // enableReducedForm
        0,                                                                  // shift
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        10,                                                                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
    {
        STATIC,                                                             // Test pattern
        staticRefInCase11,                                                  // Input matrix A
        staticRefOutUCase11,                                                // Output matrix U
        staticRefOutVCase11,                                                // Output matrix V
        staticRefOutDiagCase11,                                             // Output array Diag
        DSPLIB_FLOAT64,                                                     // precision
        7,                                                                  // widthIn
        6,                                                                  // heightIn
        DSPLIB_CALC_STRIDE(7 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // stride of A matrix
        0,                                                                  // enableReducedForm
        0,                                                                  // shift
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        11,                                                                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
    {
        STATIC,                                                             // Test pattern
        staticRefInCase12,                                                  // Input matrix A
        staticRefOutUCase12,                                                // Output matrix U
        staticRefOutVCase12,                                                // Output matrix V
        staticRefOutDiagCase12,                                             // Output array Diag
        DSPLIB_FLOAT64,                                                     // precision
        7,                                                                  // widthIn
        6,                                                                  // heightIn
        DSPLIB_CALC_STRIDE(7 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // stride of A matrix
        1,                                                                  // enableReducedForm
        0,                                                                  // shift
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        12,                                                                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
    {
        STATIC,                                                             // Test pattern
        staticRefInCase13,                                                  // Input matrix A
        staticRefOutUCase13,                                                // Output matrix U
        staticRefOutVCase13,                                                // Output matrix V
        staticRefOutDiagCase13,                                             // Output array Diag
        DSPLIB_FLOAT64,                                                     // precision
        6,                                                                  // widthIn
        6,                                                                  // heightIn
        DSPLIB_CALC_STRIDE(6 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // stride of A matrix
        0,                                                                  // enableReducedForm
        0,                                                                  // shift
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        13,                                                                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
    {
        STATIC,                                                             // Test pattern
        staticRefInCase14,                                                  // Input matrix A
        staticRefOutUCase14,                                                // Output matrix U
        staticRefOutVCase14,                                                // Output matrix V
        staticRefOutDiagCase14,                                             // Output array Diag
        DSPLIB_FLOAT64,                                                     // precision
        6,                                                                  // widthIn
        6,                                                                  // heightIn
        DSPLIB_CALC_STRIDE(6 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // stride of A matrix
        1,                                                                  // enableReducedForm
        0,                                                                  // shift
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        14,                                                                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
    {
        STATIC,                                                             // Test pattern
        staticRefInCase15,                                                  // Input matrix A
        staticRefOutUCase15,                                                // Output matrix U
        staticRefOutVCase15,                                                // Output matrix V
        staticRefOutDiagCase15,                                             // Output array Diag
        DSPLIB_FLOAT64,                                                     // precision
        7,                                                                  // widthIn
        6,                                                                  // heightIn
        DSPLIB_CALC_STRIDE(7 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // stride of A matrix
        0,                                                                  // enableReducedForm
        0,                                                                  // shift
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        15,                                                                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
    {
        STATIC,                                                             // Test pattern
        staticRefInCase16,                                                  // Input matrix A
        staticRefOutUCase16,                                                // Output matrix U
        staticRefOutVCase16,                                                // Output matrix V
        staticRefOutDiagCase16,                                             // Output array Diag
        DSPLIB_FLOAT64,                                                     // precision
        7,                                                                  // widthIn
        6,                                                                  // heightIn
        DSPLIB_CALC_STRIDE(7 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // stride of A matrix
        1,                                                                  // enableReducedForm
        0,                                                                  // shift
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        16,                                                                 // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void DSPLIB_svd_small_getTestParams(DSPLIB_svd_small_testParams_t** params, int32_t* numTests)
{
   *params   = testParams;
   *numTests = sizeof(testParams) / sizeof(DSPLIB_svd_small_testParams_t);
}
