// Copyright (C) 2026 Texas Instruments Incorporated
//
// SPDX-License-Identifier: Apache-2.0

#include "DSPLIB_blkCopyConst2D_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
#include "test_data/staticRefCase21.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
#include "test_data/staticRefCase22.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
#include "test_data/staticRefCase23.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
#include "test_data/staticRefCase24.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 25))
#include "test_data/staticRefCase25.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 26))
#include "test_data/staticRefCase26.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 27))
#include "test_data/staticRefCase27.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 28))
#include "test_data/staticRefCase28.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 29))
#include "test_data/staticRefCase29.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 30))
#include "test_data/staticRefCase30.h"
#endif

static DSPLIB_blkCopyConst2D_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
    {
        STATIC,                  // Test pattern
        staticRefIn1Case1,       // Input buffer
        staticRefOutCase1,       // Output vector
        DSPLIB_FLOAT32,          // precision
        32,                      // Number of samples in a vector
        4,                       // Number of channels in a vector
        32 * sizeof(float),      // stride of output buffer
        1,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        1,                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
    {
        STATIC,                  // Test pattern
        staticRefIn1Case2,       // Input buffer
        staticRefOutCase2,       // Output vector
        DSPLIB_UINT8,            // precision
        64,                      // Number of samples in a vector
        8,                       // Number of channels in a vector
        64 * sizeof(uint8_t),    // stride of output buffer
        -2,                      // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        2,                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
    {
        STATIC,                  // Test pattern
        staticRefIn1Case3,       // Input buffer
        staticRefOutCase3,       // Output vector
        DSPLIB_INT8,             // precision
        128,                     // Number of samples in a vector
        16,                      // Number of channels in a vector
        128 * sizeof(int8_t),    // stride of output buffer
        3,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        3,                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
    {
        STATIC,                  // Test pattern
        staticRefIn1Case4,       // Input buffer
        staticRefOutCase4,       // Output vector
        DSPLIB_UINT16,           // precision
        256,                     // Number of samples in a vector
        64,                      // Number of channels in a vector
        256 * sizeof(uint16_t),  // stride of output buffer
        4,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        4,                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
    {
        STATIC,                  // Test pattern
        staticRefIn1Case5,       // Input buffer
        staticRefOutCase5,       // Output vector
        DSPLIB_INT16,            // precision
        512,                     // Number of samples in a vector
        15,                      // Number of channels in a vector
        512 * sizeof(int16_t),   // stride of output buffer
        5,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        5,                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
    {
        STATIC,                  // Test pattern
        staticRefIn1Case6,       // Input buffer
        staticRefOutCase6,       // Output vector
        DSPLIB_UINT32,           // precision
        29,                      // Number of samples in a vector
        32,                      // Number of channels in a vector
        29 * sizeof(uint32_t),   // stride of output buffer
        6,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        6,                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
    {
        STATIC,                  // Test pattern
        staticRefIn1Case7,       // Input buffer
        staticRefOutCase7,       // Output vector
        DSPLIB_INT32,            // precision
        65,                      // Number of samples in a vector
        27,                      // Number of channels in a vector
        65 * sizeof(int32_t),    // stride of output buffer
        7,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        7,                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
    {
        STATIC,                  // Test pattern
        staticRefIn1Case8,       // Input buffer
        staticRefOutCase8,       // Output vector
        DSPLIB_UINT64,           // precision
        48,                      // Number of samples in a vector
        17,                      // Number of channels in a vector
        48 * sizeof(uint64_t),   // stride of output buffer
        8,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        8,                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
    {
        STATIC,                  // Test pattern
        staticRefIn1Case9,       // Input buffer
        staticRefOutCase9,       // Output vector
        DSPLIB_INT64,            // precision
        100,                     // Number of samples in a vector
        24,                      // Number of channels in a vector
        100 * sizeof(int64_t),   // stride of output buffer
        9,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        9,                       // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
    {
        STATIC,                  // Test pattern
        staticRefIn1Case10,      // Input buffer
        staticRefOutCase10,      // Output vector
        DSPLIB_FLOAT64,          // precision
        97,                      // Number of samples in a vector
        11,                      // Number of channels in a vector
        97 * sizeof(double),     // stride of output buffer
        10,                      // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        10,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
    {
        RANDOM,                  // Test pattern
        NULL,                    // Input buffer
        NULL,                    // Output vector
        DSPLIB_FLOAT32,          // precision
        32,                      // Number of samples in a vector
        4,                       // Number of channels in a vector
        32 * sizeof(float),      // stride of output buffer
        1,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        11,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
    {
        RANDOM,                  // Test pattern
        NULL,                    // Input buffer
        NULL,                    // Output vector
        DSPLIB_UINT8,            // precision
        64,                      // Number of samples in a vector
        8,                       // Number of channels in a vector
        64 * sizeof(uint8_t),    // stride of output buffer
        2,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        12,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
    {
        RANDOM,                  // Test pattern
        NULL,                    // Input buffer
        NULL,                    // Output vector
        DSPLIB_INT8,             // precision
        128,                     // Number of samples in a vector
        16,                      // Number of channels in a vector
        128 * sizeof(int8_t),    // stride of output buffer
        3,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        13,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
    {
        RANDOM,                  // Test pattern
        NULL,                    // Input buffer
        NULL,                    // Output vector
        DSPLIB_UINT16,           // precision
        256,                     // Number of samples in a vector
        64,                      // Number of channels in a vector
        256 * sizeof(uint16_t),  // stride of output buffer
        4,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        14,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
    {
        RANDOM,                  // Test pattern
        NULL,                    // Input buffer
        NULL,                    // Output vector
        DSPLIB_INT16,            // precision
        512,                     // Number of samples in a vector
        15,                      // Number of channels in a vector
        512 * sizeof(int16_t),   // stride of output buffer
        5,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        15,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
    {
        RANDOM,                  // Test pattern
        NULL,                    // Input buffer
        NULL,                    // Output vector
        DSPLIB_UINT32,           // precision
        29,                      // Number of samples in a vector
        32,                      // Number of channels in a vector
        29 * sizeof(uint32_t),   // stride of output buffer
        6,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        16,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
    {
        RANDOM,                  // Test pattern
        NULL,                    // Input buffer
        NULL,                    // Output vector
        DSPLIB_INT32,            // precision
        65,                      // Number of samples in a vector
        27,                      // Number of channels in a vector
        65 * sizeof(int32_t),    // stride of output buffer
        7,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        17,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
    {
        RANDOM,                  // Test pattern
        NULL,                    // Input buffer
        NULL,                    // Output vector
        DSPLIB_UINT64,           // precision
        48,                      // Number of samples in a vector
        17,                      // Number of channels in a vector
        48 * sizeof(uint64_t),   // stride of output buffer
        8,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        18,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
    {
        RANDOM,                  // Test pattern
        NULL,                    // Input buffer
        NULL,                    // Output vector
        DSPLIB_INT64,            // precision
        100,                     // Number of samples in a vector
        24,                      // Number of channels in a vector
        100 * sizeof(int64_t),   // stride of output buffer
        9,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        19,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
    {
        RANDOM,                  // Test pattern
        NULL,                    // Input buffer
        NULL,                    // Output vector
        DSPLIB_FLOAT64,          // precision
        97,                      // Number of samples in a vector
        11,                      // Number of channels in a vector
        97 * sizeof(double),     // stride of output buffer
        10,                      // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        20,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
    {
        STATIC,                  // Test pattern
        staticRefIn1Case21,      // Input buffer
        staticRefOutCase21,      // Output vector
        DSPLIB_FLOAT32,          // precision
        32,                      // Number of samples in a vector
        4,                       // Number of channels in a vector
        32 * sizeof(float),      // stride of output buffer
        1,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        21,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
    {
        STATIC,                  // Test pattern
        staticRefIn1Case22,      // Input buffer
        staticRefOutCase22,      // Output vector
        DSPLIB_UINT8,            // precision
        64,                      // Number of samples in a vector
        8,                       // Number of channels in a vector
        64 * sizeof(uint8_t),    // stride of output buffer
        -2,                      // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        22,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
    {
        STATIC,                  // Test pattern
        staticRefIn1Case23,      // Input buffer
        staticRefOutCase23,      // Output vector
        DSPLIB_INT8,             // precision
        128,                     // Number of samples in a vector
        16,                      // Number of channels in a vector
        128 * sizeof(int8_t),    // stride of output buffer
        3,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        23,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
    {
        STATIC,                  // Test pattern
        staticRefIn1Case24,      // Input buffer
        staticRefOutCase24,      // Output vector
        DSPLIB_UINT16,           // precision
        256,                     // Number of samples in a vector
        10,                      // Number of channels in a vector
        256 * sizeof(uint16_t),  // stride of output buffer
        4,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        24,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 25))
    {
        STATIC,                  // Test pattern
        staticRefIn1Case25,      // Input buffer
        staticRefOutCase25,      // Output vector
        DSPLIB_INT16,            // precision
        512,                     // Number of samples in a vector
        15,                      // Number of channels in a vector
        512 * sizeof(int16_t),   // stride of output buffer
        5,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        25,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 26))
    {
        STATIC,                  // Test pattern
        staticRefIn1Case26,      // Input buffer
        staticRefOutCase26,      // Output vector
        DSPLIB_UINT32,           // precision
        29,                      // Number of samples in a vector
        32,                      // Number of channels in a vector
        29 * sizeof(uint32_t),   // stride of output buffer
        6,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        26,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 27))
    {
        STATIC,                  // Test pattern
        staticRefIn1Case27,      // Input buffer
        staticRefOutCase27,      // Output vector
        DSPLIB_INT32,            // precision
        65,                      // Number of samples in a vector
        27,                      // Number of channels in a vector
        65 * sizeof(int32_t),    // stride of output buffer
        7,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        27,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 28))
    {
        STATIC,                  // Test pattern
        staticRefIn1Case28,      // Input buffer
        staticRefOutCase28,      // Output vector
        DSPLIB_UINT64,           // precision
        48,                      // Number of samples in a vector
        17,                      // Number of channels in a vector
        48 * sizeof(uint64_t),   // stride of output buffer
        8,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        28,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 29))
    {
        STATIC,                  // Test pattern
        staticRefIn1Case29,      // Input buffer
        staticRefOutCase29,      // Output vector
        DSPLIB_INT64,            // precision
        100,                     // Number of samples in a vector
        24,                      // Number of channels in a vector
        100 * sizeof(int64_t),   // stride of output buffer
        9,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        29,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 30))
    {
        STATIC,                  // Test pattern
        staticRefIn1Case30,      // Input buffer
        staticRefOutCase30,      // Output vector
        DSPLIB_FLOAT64,          // precision
        97,                      // Number of samples in a vector
        11,                      // Number of channels in a vector
        97 * sizeof(double),     // stride of output buffer
        10,                      // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        30,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 31))
    {
        RANDOM,                  // Test pattern
        NULL,                    // Input buffer
        NULL,                    // Output vector
        DSPLIB_FLOAT32,          // precision
        32,                      // Number of samples in a vector
        4,                       // Number of channels in a vector
        32 * sizeof(float),      // stride of output buffer
        1,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        31,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 32))
    {
        RANDOM,                  // Test pattern
        NULL,                    // Input buffer
        NULL,                    // Output vector
        DSPLIB_UINT8,            // precision
        64,                      // Number of samples in a vector
        8,                       // Number of channels in a vector
        64 * sizeof(uint8_t),    // stride of output buffer
        2,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        32,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 33))
    {
        RANDOM,                  // Test pattern
        NULL,                    // Input buffer
        NULL,                    // Output vector
        DSPLIB_INT8,             // precision
        128,                     // Number of samples in a vector
        16,                      // Number of channels in a vector
        128 * sizeof(int8_t),    // stride of output buffer
        3,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        33,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 34))
    {
        RANDOM,                  // Test pattern
        NULL,                    // Input buffer
        NULL,                    // Output vector
        DSPLIB_UINT16,           // precision
        256,                     // Number of samples in a vector
        10,                      // Number of channels in a vector
        256 * sizeof(uint16_t),  // stride of output buffer
        4,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        34,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 35))
    {
        RANDOM,                  // Test pattern
        NULL,                    // Input buffer
        NULL,                    // Output vector
        DSPLIB_INT16,            // precision
        512,                     // Number of samples in a vector
        15,                      // Number of channels in a vector
        512 * sizeof(int16_t),   // stride of output buffer
        5,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        35,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 36))
    {
        RANDOM,                  // Test pattern
        NULL,                    // Input buffer
        NULL,                    // Output vector
        DSPLIB_UINT32,           // precision
        29,                      // Number of samples in a vector
        32,                      // Number of channels in a vector
        29 * sizeof(uint32_t),   // stride of output buffer
        6,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        36,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 37))
    {
        RANDOM,                  // Test pattern
        NULL,                    // Input buffer
        NULL,                    // Output vector
        DSPLIB_INT32,            // precision
        65,                      // Number of samples in a vector
        27,                      // Number of channels in a vector
        65 * sizeof(int32_t),    // stride of output buffer
        7,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        37,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 38))
    {
        RANDOM,                  // Test pattern
        NULL,                    // Input buffer
        NULL,                    // Output vector
        DSPLIB_UINT64,           // precision
        48,                      // Number of samples in a vector
        17,                      // Number of channels in a vector
        48 * sizeof(uint64_t),   // stride of output buffer
        8,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        38,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 39))
    {
        RANDOM,                  // Test pattern
        NULL,                    // Input buffer
        NULL,                    // Output vector
        DSPLIB_INT64,            // precision
        100,                     // Number of samples in a vector
        24,                      // Number of channels in a vector
        100 * sizeof(int64_t),   // stride of output buffer
        9,                       // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        39,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 40))
    {
        RANDOM,                  // Test pattern
        NULL,                    // Input buffer
        NULL,                    // Output vector
        DSPLIB_FLOAT64,          // precision
        97,                      // Number of samples in a vector
        11,                      // Number of channels in a vector
        97 * sizeof(double),     // stride of output buffer
        10,                      // constant
        DSPLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                       // number of reps.
        40,                      // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void DSPLIB_blkCopyConst2D_getTestParams(DSPLIB_blkCopyConst2D_testParams_t** params, int32_t* numTests)
{
   *params   = testParams;
   *numTests = sizeof(testParams) / sizeof(DSPLIB_blkCopyConst2D_testParams_t);
}
