// Copyright (C) 2026 Texas Instruments Incorporated
//
// SPDX-License-Identifier: Apache-2.0

#include "DSPLIB_realImagToComplex_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
#include "test_data/staticRefCase12.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
#include "test_data/staticRefCase13.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
#include "test_data/staticRefCase14.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
#include "test_data/staticRefCase15.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
#include "test_data/staticRefCase16.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
#include "test_data/staticRefCase17.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
#include "test_data/staticRefCase18.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
#include "test_data/staticRefCase19.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
#include "test_data/staticRefCase20.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
#include "test_data/staticRefCase21.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
#include "test_data/staticRefCase22.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
#include "test_data/staticRefCase23.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
#include "test_data/staticRefCase24.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 25))
#include "test_data/staticRefCase25.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 26))
#include "test_data/staticRefCase26.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 27))
#include "test_data/staticRefCase27.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 28))
#include "test_data/staticRefCase28.h"
#endif

static DSPLIB_realImagToComplex_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
    {
        STATIC,                                                               // Test pattern
        staticRefIn0Case1,                                                    // Input buffer
        staticRefIn1Case1,                                                    // Input realImagToComplex
        staticRefOutCase1,                                                    // Output buffer
        1025,                                                                 // inSamples
        3,                                                                    // inChannels
        DSPLIB_CALC_STRIDE(1025 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(1025 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_FLOAT32,                                                       // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                    // number of reps.
        1,                                                                    // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
    {
        STATIC,                                                             // Test pattern
        staticRefIn0Case2,                                                  // Input buffer
        staticRefIn1Case2,                                                  // Input realImagToComplex
        staticRefOutCase2,                                                  // Output buffer
        32,                                                                 // inSamples
        16,                                                                 // inChannels
        DSPLIB_CALC_STRIDE(32 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(32 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_FLOAT32,                                                     // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        2,                                                                  // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
    {
        STATIC,                                                             // Test pattern
        staticRefIn0Case3,                                                  // Input buffer
        staticRefIn1Case3,                                                  // Input realImagToComplex
        staticRefOutCase3,                                                  // Output buffer
        64,                                                                 // inSamples
        64,                                                                 // inChannels
        DSPLIB_CALC_STRIDE(64 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(64 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_FLOAT32,                                                     // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        3,                                                                  // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
    {
        STATIC,                                                            // Test pattern
        staticRefIn0Case4,                                                 // Input buffer
        staticRefIn1Case4,                                                 // Input realImagToComplex
        staticRefOutCase4,                                                 // Output buffer
        1,                                                                 // inSamples
        3,                                                                 // inChannels
        DSPLIB_CALC_STRIDE(1 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(1 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_FLOAT32,                                                    // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                           // Output data location
        1,                                                                 // number of reps.
        4,                                                                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
    {
        STATIC,                                                               // Test pattern
        staticRefIn0Case5,                                                    // Input buffer
        staticRefIn1Case5,                                                    // Input realImagToComplex
        staticRefOutCase5,                                                    // Output buffer
        1024,                                                                 // inSamples
        3,                                                                    // inChannels
        DSPLIB_CALC_STRIDE(1024 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(1024 * sizeof(float), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_FLOAT32,                                                       // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                    // number of reps.
        5,                                                                    // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
    {
        STATIC,                                                                // Test pattern
        staticRefIn0Case6,                                                     // Input buffer
        staticRefIn1Case6,                                                     // Input realImagToComplex
        staticRefOutCase6,                                                     // Output buffer
        1025,                                                                  // inSamples
        5,                                                                     // inChannels
        DSPLIB_CALC_STRIDE(1025 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(1025 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_FLOAT64,                                                        // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                     // number of reps.
        6,                                                                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
    {
        STATIC,                                                              // Test pattern
        staticRefIn0Case7,                                                   // Input buffer
        staticRefIn1Case7,                                                   // Input realImagToComplex
        staticRefOutCase7,                                                   // Output buffer
        16,                                                                  // inSamples
        128,                                                                 // inChannels
        DSPLIB_CALC_STRIDE(16 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(16 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_FLOAT64,                                                      // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                             // Output data location
        1,                                                                   // number of reps.
        7,                                                                   // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
    {
        STATIC,                                                               // Test pattern
        staticRefIn0Case8,                                                    // Input buffer
        staticRefIn1Case8,                                                    // Input realImagToComplex
        staticRefOutCase8,                                                    // Output buffer
        128,                                                                  // inSamples
        16,                                                                   // inChannels
        DSPLIB_CALC_STRIDE(128 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(128 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_FLOAT64,                                                       // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                    // number of reps.
        8,                                                                    // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
    {
        STATIC,                                                             // Test pattern
        staticRefIn0Case9,                                                  // Input buffer
        staticRefIn1Case9,                                                  // Input realImagToComplex
        staticRefOutCase9,                                                  // Output buffer
        1,                                                                  // inSamples
        1,                                                                  // inChannels
        DSPLIB_CALC_STRIDE(1 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(1 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_FLOAT64,                                                     // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                            // Output data location
        1,                                                                  // number of reps.
        9,                                                                  // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
    {
        STATIC,                                                                // Test pattern
        staticRefIn0Case10,                                                    // Input buffer
        staticRefIn1Case10,                                                    // Input realImagToComplex
        staticRefOutCase10,                                                    // Output buffer
        2048,                                                                  // inSamples
        7,                                                                     // inChannels
        DSPLIB_CALC_STRIDE(2048 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(2048 * sizeof(double), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_FLOAT64,                                                        // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                     // number of reps.
        10,                                                                    // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case11,                                                     // Input buffer
        staticRefIn1Case11,                                                     // Input realImagToComplex
        staticRefOutCase11,                                                     // Output buffer
        1055,                                                                   // inSamples
        11,                                                                     // inChannels
        DSPLIB_CALC_STRIDE(1055 * sizeof(int16_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(1055 * sizeof(int16_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_INT16,                                                           // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                      // number of reps.
        11,                                                                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
    {
        STATIC,                                                                // Test pattern
        staticRefIn0Case12,                                                    // Input buffer
        staticRefIn1Case12,                                                    // Input realImagToComplex
        staticRefOutCase12,                                                    // Output buffer
        128,                                                                   // inSamples
        128,                                                                   // inChannels
        DSPLIB_CALC_STRIDE(128 * sizeof(int16_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(128 * sizeof(int16_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_INT16,                                                          // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                     // number of reps.
        12,                                                                    // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
    {
        STATIC,                                                                // Test pattern
        staticRefIn0Case13,                                                    // Input buffer
        staticRefIn1Case13,                                                    // Input realImagToComplex
        staticRefOutCase13,                                                    // Output buffer
        128,                                                                   // inSamples
        64,                                                                    // inChannels
        DSPLIB_CALC_STRIDE(128 * sizeof(int16_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(128 * sizeof(int16_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_INT16,                                                          // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                     // number of reps.
        13,                                                                    // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
    {
        STATIC,                                                               // Test pattern
        staticRefIn0Case14,                                                   // Input buffer
        staticRefIn1Case14,                                                   // Input realImagToComplex
        staticRefOutCase14,                                                   // Output buffer
        64,                                                                   // inSamples
        64,                                                                   // inChannels
        DSPLIB_CALC_STRIDE(64 * sizeof(int16_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(64 * sizeof(int16_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_INT16,                                                         // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                    // number of reps.
        14,                                                                   // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
    {
        STATIC,                                                               // Test pattern
        staticRefIn0Case15,                                                   // Input buffer
        staticRefIn1Case15,                                                   // Input realImagToComplex
        staticRefOutCase15,                                                   // Output buffer
        10,                                                                   // inSamples
        3,                                                                    // inChannels
        DSPLIB_CALC_STRIDE(10 * sizeof(int16_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(10 * sizeof(int16_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_INT16,                                                         // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                    // number of reps.
        15,                                                                   // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case16,                                                      // Input buffer
        staticRefIn1Case16,                                                      // Input realImagToComplex
        staticRefOutCase16,                                                      // Output buffer
        1025,                                                                    // inSamples
        10,                                                                      // inChannels
        DSPLIB_CALC_STRIDE(1025 * sizeof(uint16_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(1025 * sizeof(uint16_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_UINT16,                                                           // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                                 // Output data location
        1,                                                                       // number of reps.
        16,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case17,                                                      // Input buffer
        staticRefIn1Case17,                                                      // Input realImagToComplex
        staticRefOutCase17,                                                      // Output buffer
        1024,                                                                    // inSamples
        1,                                                                       // inChannels
        DSPLIB_CALC_STRIDE(1024 * sizeof(uint16_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(1024 * sizeof(uint16_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_UINT16,                                                           // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                                 // Output data location
        1,                                                                       // number of reps.
        17,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case18,                                                     // Input buffer
        staticRefIn1Case18,                                                     // Input realImagToComplex
        staticRefOutCase18,                                                     // Output buffer
        128,                                                                    // inSamples
        64,                                                                     // inChannels
        DSPLIB_CALC_STRIDE(128 * sizeof(uint16_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(128 * sizeof(uint16_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_UINT16,                                                          // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                      // number of reps.
        18,                                                                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
    {
        STATIC,                                                               // Test pattern
        staticRefIn0Case19,                                                   // Input buffer
        staticRefIn1Case19,                                                   // Input realImagToComplex
        staticRefOutCase19,                                                   // Output buffer
        1,                                                                    // inSamples
        3,                                                                    // inChannels
        DSPLIB_CALC_STRIDE(1 * sizeof(uint16_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(1 * sizeof(uint16_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_UINT16,                                                        // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                    // number of reps.
        19,                                                                   // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case20,                                                      // Input buffer
        staticRefIn1Case20,                                                      // Input realImagToComplex
        staticRefOutCase20,                                                      // Output buffer
        2048,                                                                    // inSamples
        3,                                                                       // inChannels
        DSPLIB_CALC_STRIDE(2048 * sizeof(uint16_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(2048 * sizeof(uint16_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_UINT16,                                                           // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                                 // Output data location
        1,                                                                       // number of reps.
        20,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case21,                                                      // Input buffer
        staticRefIn1Case21,                                                      // Input realImagToComplex
        staticRefOutCase21,                                                      // Output buffer
        1000,                                                                    // inSamples
        2,                                                                       // inChannels
        DSPLIB_CALC_STRIDE(1000 * sizeof(uint32_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(1000 * sizeof(uint32_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_UINT32,                                                           // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                                 // Output data location
        1,                                                                       // number of reps.
        21,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
    {
        STATIC,                                                                  // Test pattern
        staticRefIn0Case22,                                                      // Input buffer
        staticRefIn1Case22,                                                      // Input realImagToComplex
        staticRefOutCase22,                                                      // Output buffer
        1024,                                                                    // inSamples
        3,                                                                       // inChannels
        DSPLIB_CALC_STRIDE(1024 * sizeof(uint32_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(1024 * sizeof(uint32_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_UINT32,                                                           // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                                 // Output data location
        1,                                                                       // number of reps.
        22,                                                                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23))
    {
        STATIC,                                                                // Test pattern
        staticRefIn0Case23,                                                    // Input buffer
        staticRefIn1Case23,                                                    // Input realImagToComplex
        staticRefOutCase23,                                                    // Output buffer
        64,                                                                    // inSamples
        64,                                                                    // inChannels
        DSPLIB_CALC_STRIDE(64 * sizeof(uint32_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(64 * sizeof(uint32_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_UINT32,                                                         // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                     // number of reps.
        23,                                                                    // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 24))
    {
        STATIC,                                                                // Test pattern
        staticRefIn0Case24,                                                    // Input buffer
        staticRefIn1Case24,                                                    // Input realImagToComplex
        staticRefOutCase24,                                                    // Output buffer
        10,                                                                    // inSamples
        1,                                                                     // inChannels
        DSPLIB_CALC_STRIDE(10 * sizeof(uint32_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(10 * sizeof(uint32_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_UINT32,                                                         // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                     // number of reps.
        24,                                                                    // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 25))
    {
        STATIC,                                                                // Test pattern
        staticRefIn0Case25,                                                    // Input buffer
        staticRefIn1Case25,                                                    // Input realImagToComplex
        staticRefOutCase25,                                                    // Output buffer
        900,                                                                   // inSamples
        16,                                                                    // inChannels
        DSPLIB_CALC_STRIDE(900 * sizeof(int32_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(900 * sizeof(int32_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_INT32,                                                          // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                               // Output data location
        1,                                                                     // number of reps.
        25,                                                                    // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 26))
    {
        STATIC,                                                                 // Test pattern
        staticRefIn0Case26,                                                     // Input buffer
        staticRefIn1Case26,                                                     // Input realImagToComplex
        staticRefOutCase26,                                                     // Output buffer
        1025,                                                                   // inSamples
        3,                                                                      // inChannels
        DSPLIB_CALC_STRIDE(1025 * sizeof(int32_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(1025 * sizeof(int32_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_INT32,                                                           // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                                // Output data location
        1,                                                                      // number of reps.
        26,                                                                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 27))
    {
        STATIC,                                                               // Test pattern
        staticRefIn0Case27,                                                   // Input buffer
        staticRefIn1Case27,                                                   // Input realImagToComplex
        staticRefOutCase27,                                                   // Output buffer
        64,                                                                   // inSamples
        128,                                                                  // inChannels
        DSPLIB_CALC_STRIDE(64 * sizeof(int32_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(64 * sizeof(int32_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_INT32,                                                         // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                    // number of reps.
        27,                                                                   // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 28))
    {
        STATIC,                                                               // Test pattern
        staticRefIn0Case28,                                                   // Input buffer
        staticRefIn1Case28,                                                   // Input realImagToComplex
        staticRefOutCase28,                                                   // Output buffer
        64,                                                                   // inSamples
        64,                                                                   // inChannels
        DSPLIB_CALC_STRIDE(64 * sizeof(int32_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0
        DSPLIB_CALC_STRIDE(64 * sizeof(int32_t), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut
        DSPLIB_INT32,                                                         // precision
        DSPLIB_TEST_OUTPUT_MSMC,                                              // Output data location
        1,                                                                    // number of reps.
        28,                                                                   // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void DSPLIB_realImagToComplex_getTestParams(DSPLIB_realImagToComplex_testParams_t** params, int32_t* numTests)
{
   *params   = testParams;
   *numTests = sizeof(testParams) / sizeof(DSPLIB_realImagToComplex_testParams_t);
}
