# Copyright (C) 2026 Texas Instruments Incorporated
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import print_function
from subprocess import call
from sys import platform

import sys
import numpy as np
import csv

sys.path.append("../common")
import DSPLIB_utils
import file_io


def gen_testCaseParams(testParamsFile, currPrm):
    """Generate and write test case parameters to idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    testType = currPrm["testType"]
    dTypeIn = currPrm["dTypeIn"]
    dTypeOut = currPrm["dTypeOut"]
    dTypeFilter = currPrm["dTypeFilter"]
    dataSize = currPrm["dataSize"]
    filterSize = currPrm["filterSize"]
    demoCase = currPrm["demoCase"]
    numReps = currPrm["numReps"]
    outputDataLocation = currPrm["outputDataLocation"]
    enableNChCoefs = currPrm["enableNChCoefs"]
    enableMMA = currPrm["enableMMA"]
    enableQ = currPrm["enableQ"]
    Q = currPrm["Q"]
    testId = currPrm["ID"]
    batchSize = currPrm["batchSize"]
    outSize = dataSize - filterSize + 1

    if testType == "STATIC":
        inputData = "staticRefInCase" + testId
        filterData = "staticRefFilterCase" + testId
        outputData = "staticRefOutCase" + testId
    else:
        inputData = "NULL"
        filterData = "NULL"
        outputData = "NULL"

    if demoCase == "true":
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d) || defined(DEMO_CASE))\n"
            % (int(testId))
        )
    else:
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d))\n" % (int(testId))
        )

    DSPLIB_dTypeIn = DSPLIB_utils.resolve_dType(dTypeIn)
    DSPLIB_dTypeFilter = DSPLIB_utils.resolve_dType(dTypeFilter)

    if dTypeIn == "int8_t" or dTypeIn == "uint8_t":
        sizeBytes = 1
    elif dTypeIn == "int16_t" or dTypeIn == "uint16_t":
        sizeBytes = 2
    elif dTypeIn == "int32_t" or dTypeIn == "uint32_t" or dTypeIn == "float":
        sizeBytes = 4
    else:
        sizeBytes = 8

    idatFile.write("{\n")
    idatFile.write("%s, // Test pattern \n" % ((testType)))
    idatFile.write("%s, // Input vector \n" % ((inputData)))
    idatFile.write("%s, // Filter vector \n" % ((filterData)))
    idatFile.write("%s, // Output vector \n" % ((outputData)))
    idatFile.write("%s, // datatype \n" % ((DSPLIB_dTypeIn)))
    idatFile.write("%s, // dataSize \n" % ((dataSize)))
    idatFile.write("%s, // dataPitchIn \n" % ((dataSize * sizeBytes)))
    idatFile.write("%s, // dataPitchOut \n" % ((outSize * sizeBytes)))
    idatFile.write("%s, // batchSize \n" % ((batchSize)))
    idatFile.write("%s, // filterSize \n" % ((filterSize)))
    idatFile.write("%s, // filterPitch \n" % ((filterSize * sizeBytes)))
    idatFile.write("%s, // enableNchCoefs\n" % ((enableNChCoefs)))
    idatFile.write("%s, // enableMMA \n" % ((enableMMA)))
    idatFile.write("%s, // enableQ \n" % ((enableQ)))
    idatFile.write("%s, // Q \n" % ((Q)))
    idatFile.write("%s, // Output data location \n" % (outputDataLocation))
    idatFile.write("%d, // number of reps. \n" % (int(numReps)))
    idatFile.write("%d, // test ID\n" % int(testId))
    idatFile.write("},\n")
    idatFile.write("#endif")
    idatFile.write("\n\n")


def gen_idat_file(idatFile, testCases):
    """Generate the idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    fIn = open("../common/ti_lice_header_idat.txt", "r")
    lines = fIn.readlines()
    fIn.close()
    idatFile.writelines(lines)
    includeString = '#include "DSPLIB_fir_idat.h"'
    idatFile.writelines(includeString)
    idatFile.write("\n")
    idatFile.write("/*This file is autogenerated*/\n")
    idatFile.write("/*Please do not edit*/\n")
    idatFile.write("\n\n")
    # generate ifdefs for header files
    for testCase in testCases:
        if testCase["testType"] == "STATIC":
            DSPLIB_utils.gen_ifdefs(idatFile, testCase)

    # generate parameters for test cases
    idatFile.write("static DSPLIB_fir_testParams_t testParams[] =  ")
    idatFile.write("{\n")

    for testCase in testCases:
        gen_testCaseParams(idatFile, testCase)

    idatFile.write("};\n\n")
    fIn = open("test_param_function.txt", "r")
    lines = fIn.readlines()

    idatFile.writelines(lines)


def process_test_case(testCase):
    """Convert str to int for necessary parameters

    Args:
        Param1(:obj: dict) : Dictionary object with test case parameters

    Returns:
        Obj: Dictionary object with necessary parameters converted to int

    """

    # print(testCase.keys())
    testCase["dataSize"] = int(testCase["dataSize"])
    testCase["filterSize"] = int(testCase["filterSize"])
    testCase["enableMMA"] = int(testCase["enableMMA"])
    testCase["enableNChCoefs"] = int(testCase["enableNChCoefs"])
    testCase["batchSize"] = int(testCase["batchSize"])
    testCase["enableQ"] = int(testCase["enableQ"])
    testCase["Q"] = int(testCase["Q"])

    return testCase


def gen_test_case_header_file(testCase):
    """Generate test case and write out input, filter, and output tensor
    into a header file usable in C/C++ code.

    Args:
        param1 (:obj: dict): A dict object with all the test case
        parameters

    Returns:
        [int int]: Minimum and maximum value in output feature tensor

    """

    ##############################
    # Get test parameter of case #
    ##############################

    testId = testCase["ID"]
    dataSize = testCase["dataSize"]
    dTypeIn = testCase["dTypeIn"]
    filterSize = testCase["filterSize"]
    dTypeFilter = testCase["dTypeFilter"]
    filterSize = testCase["filterSize"]
    batchSize = testCase["batchSize"]
    enableNChCoefs = testCase["enableNChCoefs"]

    if dTypeIn == "int8_t" or dTypeIn == "uint8_t":
        bits = 8
    elif dTypeIn == "int16_t" or dTypeIn == "uint16_t":
        bits = 16
    elif dTypeIn == "int32_t" or dTypeIn == "uint32_t" or dTypeIn == "float":
        bits = 32
    else:
        bits = 64

    # unsigned integer
    if dTypeIn[0] == "u":
        minVal = 0
        maxVal = (2**bits) - 1
    else:
        minVal = -(2 ** (bits - 1))
        maxVal = 2 ** (bits - 1)

    # determine filter height
    if enableNChCoefs == 1:
        filterHeight = batchSize
    else:
        filterHeight = 1

    if dTypeIn == "int8_t":
        inputData = np.random.uniform(
            low=minVal, high=maxVal, size=(batchSize, dataSize)
        ).astype("int8")
        filterData = np.random.uniform(
            low=minVal, high=maxVal, size=(filterHeight, filterSize)
        ).astype("int8")
    elif dTypeIn == "int16_t":
        inputData = np.random.uniform(
            low=minVal, high=maxVal, size=(batchSize, dataSize)
        ).astype("int16")
        filterData = np.random.uniform(
            low=minVal, high=maxVal, size=(filterHeight, filterSize)
        ).astype("int16")
    elif dTypeIn == "int32_t":
        inputData = np.random.uniform(
            low=minVal, high=maxVal, size=(batchSize, dataSize)
        ).astype("int32")
        filterData = np.random.uniform(
            low=minVal, high=maxVal, size=(filterHeight, filterSize)
        ).astype("int32")
    elif dTypeIn == "int64_t":
        inputData = np.random.uniform(
            low=minVal, high=maxVal, size=(batchSize, dataSize)
        ).astype("int64")
        filterData = np.random.uniform(
            low=minVal, high=maxVal, size=(filterHeight, filterSize)
        ).astype("int64")
    elif dTypeIn == "uint8_t":
        inputData = np.random.uniform(
            low=minVal, high=maxVal, size=(batchSize, dataSize)
        ).astype("uint8")
        filterData = np.random.uniform(
            low=minVal, high=maxVal, size=(filterHeight, filterSize)
        ).astype("uint8")
    elif dTypeIn == "uint16_t":
        inputData = np.random.uniform(
            low=minVal, high=maxVal, size=(batchSize, dataSize)
        ).astype("uint16")
        filterData = np.random.uniform(
            low=minVal, high=maxVal, size=(filterHeight, filterSize)
        ).astype("uint16")
    elif dTypeIn == "uint32_t":
        inputData = np.random.uniform(
            low=minVal, high=maxVal, size=(batchSize, dataSize)
        ).astype("uint32")
        filterData = np.random.uniform(
            low=minVal, high=maxVal, size=(filterHeight, filterSize)
        ).astype("uint32")
    elif dTypeIn == "uint64_t":
        inputData = np.random.uniform(
            low=minVal, high=maxVal, size=(batchSize, dataSize)
        ).astype("uint64")
        filterData = np.random.uniform(
            low=minVal, high=maxVal, size=(filterHeight, filterSize)
        ).astype("uint64")
    elif dTypeIn == "float":
        inputData = np.random.uniform(
            low=-1, high=1, size=(batchSize, dataSize)
        ).astype("float")
        filterData = np.random.uniform(
            low=-1, high=1, size=(filterHeight, filterSize)
        ).astype("float")
    elif dTypeIn == "double":
        inputData = np.random.uniform(
            low=-1, high=1, size=(batchSize, dataSize)
        ).astype("double")
        filterData = np.random.uniform(
            low=-1, high=1, size=(filterHeight, filterSize)
        ).astype("double")

    # # normalize coefficients
    # filterSum = np.sum(np.abs(filterData), axis=1)
    # filterNorm = filterData / filterSum[:, None]
    # filterData = filterNorm

    filterData = filterData[:, ::-1]

    outSize = dataSize - filterSize + 1

    outputData = []

    # perform FIR operation

    if enableNChCoefs == 1:

        for ch in range(batchSize):
            outputData.append(
                np.convolve(
                    inputData[ch, 0:dataSize],
                    filterData[ch, 0:filterSize],
                    mode="valid",
                )
            )

    else:

        for ch in range(batchSize):
            outputData.append(
                np.convolve(
                    inputData[ch, 0:dataSize], filterData[0, 0:filterSize], mode="valid"
                )
            )

    print(np.shape(outputData))

    headerFileName = "staticRefCase" + str(testId) + ".h"
    file_io.write_header_file(
        inputData, filterData, outputData, testCase, headerFileName
    )

    return [np.min(outputData), np.max(outputData)]


# CSV file with paratmeters for all test cases
testCasesCsvFile = "test_cases_list.csv"
testIdList = []  # list of test IDs that we want to generate test data
testIdList += range(1, 553)
# testIdList = [10]


myArgs = DSPLIB_utils.getCmdLineArgs()


def gen_test_case(testCase):
    if testCase["testType"] == "STATIC":
        [minY, maxY] = gen_test_case_header_file(testCase)
        print(
            "Test case generation completed for test ID",
            testCase["ID"],
            "w/ min:",
            minY,
            "and max",
            maxY,
        )
    else:
        print(
            "Skipping test case generation for test ID",
            testCase["ID"],
            "as tesType is RANDOM",
        )


#############################################################################
# Open CSV file with test cases and generate header file with test data for #
# test cases of interest; based on testIdList                               #
#############################################################################

with open(testCasesCsvFile, encoding="utf-8-sig") as csv_file:
    testCaseReader = csv.DictReader(csv_file)
    testCases = list(testCaseReader)

    for testCase in testCases:
        testCase = process_test_case(testCase)

    for testCase in testCases:
        if myArgs.allCases == True:
            gen_test_case(testCase)
        elif int(testCase["ID"]) in testIdList:
            gen_test_case(testCase)


idatFileName = "../../DSPLIB_fir/DSPLIB_fir_idat.c"


##########################################################################
# Generate idat.cpp file by parsing all the test cases in the CSV file # #
##########################################################################


with open(idatFileName, "w") as idatFile:
    gen_idat_file(idatFile, testCases)


if platform == "linux" or platform == "linux2":
    call(["clang-format", "-style=file", "-i", idatFileName])
    call(["indent", "-nut", "-i3", "-c55", "-l200", idatFileName])
    call(["rm", idatFileName + "~"])  # remove backup file


print("Idat file generation completed")
