# Copyright (C) 2026 Texas Instruments Incorporated
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import print_function
from subprocess import call
from sys import platform

import sys
import numpy as np
import csv
import pandas as pd

sys.path.append("../common")
import DSPLIB_utils
import file_io


def gen_testCaseParams(testParamsFile, currPrm):
    """Generate and write test case parameters to idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    testId = currPrm["ID"]
    dType = currPrm["dType"]
    inInputs = currPrm["inInputs"]
    inSamples = currPrm["inSamples"]
    inChannels = currPrm["inChannels"]
    strideInElements = currPrm["strideInElements"]
    testType = currPrm["testType"]
    demoCase = currPrm["demoCase"]
    numReps = currPrm["numReps"]
    outputDataLocation = currPrm["outputDataLocation"]

    if testType == "STATIC":
        in0 = "staticRefIn0Case" + testId
        out = "staticRefOutCase" + testId
    else:
        in0 = "NULL"
        out = "NULL"

    if demoCase == "true":
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d) || defined(DEMO_CASE))\n"
            % (int(testId))
        )
    else:
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d))\n" % (int(testId))
        )

    idatFile.write("{\n")
    idatFile.write("%s, // Test pattern \n" % ((testType)))
    idatFile.write("%s, // Input vector 0 \n" % ((in0)))
    idatFile.write("%s, // Output vector \n" % ((out)))
    idatFile.write("%s, // precision \n" % (DSPLIB_utils.resolve_dType(dType)))
    idatFile.write("%s, // Number of input channels in a vector \n" % ((inInputs)))
    idatFile.write("%s, // Number of samples in a vector \n" % ((inSamples)))
    idatFile.write("%s, // Number of channels in a vector \n" % ((inChannels)))
    idatFile.write(
        "DSPLIB_CALC_STRIDE(%s * sizeof(%s), DSPLIB_ALIGN_SHIFT_64BYTES),// strideInElements buffer\n"
        % ((strideInElements), (dType))
    )
    idatFile.write("%s, // Output data location \n" % (outputDataLocation))
    idatFile.write("%d, // number of reps. \n" % (int(numReps)))
    idatFile.write("%d, // test ID\n" % int(testId))
    idatFile.write("},\n")
    idatFile.write("#endif")
    idatFile.write("\n\n")


def gen_idat_file(idatFile, testCases):
    """Generate the idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    fIn = open("../common/ti_lice_header_idat.txt", "r")
    lines = fIn.readlines()
    fIn.close()
    idatFile.writelines(lines)
    includeString = '#include "DSPLIB_addNCh_idat.h"'
    idatFile.writelines(includeString)
    idatFile.write("\n")
    idatFile.write("/*This file is autogenerated*/\n")
    idatFile.write("/*Please do not edit*/\n")
    idatFile.write("\n\n")
    # generate ifdefs for header files
    for testCase in testCases:
        if testCase["testType"] == "STATIC":
            DSPLIB_utils.gen_ifdefs(idatFile, testCase)

    # generate parameters for test cases
    idatFile.write("static DSPLIB_addNCh_testParams_t testParams[] =  ")
    idatFile.write("{\n")

    for testCase in testCases:
        gen_testCaseParams(idatFile, testCase)

    idatFile.write("};\n\n")
    fIn = open("test_param_function.txt", "r")
    lines = fIn.readlines()

    idatFile.writelines(lines)


def process_test_case(testCase):
    """Convert str to int for necessary parameters

    Args:
        Param1(:obj: dict) : Dictionary object with test case parameters

    Returns:
        Obj: Dictionary object with necessary parameters converted to int

    """

    # print(testCase.keys())
    testCase["testId"] = int(testCase["ID"])
    testCase["inSamples"] = int(testCase["inSamples"])
    testCase["inChannels"] = int(testCase["inChannels"])
    testCase["inInputs"] = int(testCase["inInputs"])

    return testCase


def gen_test_case_header_file(testCase):
    """Generate test case and write out input, filter, and output tensor
    into a header file usable in C/C++ code.

    Args:
        param1 (:obj: dict): A dict object with all the test case
        parameters

    Returns:
        [int int]: Minimum and maximum value in output feature tensor

    """

    ##############################
    # Get test parameter of case #
    ##############################

    testId = testCase["ID"]
    channels = testCase["inChannels"]
    samples = testCase["inSamples"]
    dType = testCase["dType"]
    inputs = testCase["inInputs"]

    [minVal, maxVal] = [-10, 10]

    if dType == "float":
        in0 = np.random.uniform(
            low=minVal, high=maxVal, size=(inputs, channels, samples)
        ).astype("float")
        out = np.sum(in0, axis=0).astype("float")

    elif dType == "double":
        in0 = np.random.uniform(
            low=minVal, high=maxVal, size=(inputs, channels, samples)
        ).astype("double")
        out = np.sum(in0, axis=0).astype("double")

    headerFileName = "staticRefCase" + str(testId) + ".h"

    file_io.write_header_file(in0, out, testCase, headerFileName)

    return [np.min(out), np.max(out)]


# CSV file with paratmeters for all test cases
testCasesCsvFile = "test_cases_list.csv"
df = pd.read_csv(testCasesCsvFile)
num_data_rows = len(df)
testIdList = []  # list of test IDs that we want to generate test data
testIdList += range(1, num_data_rows)


myArgs = DSPLIB_utils.getCmdLineArgs()


def gen_test_case(testCase):
    if testCase["testType"] == "STATIC":
        [minY, maxY] = gen_test_case_header_file(testCase)
        print(
            "Test case generation completed for test ID",
            testCase["ID"],
            "w/ min:",
            minY,
            "and max",
            maxY,
        )
    else:
        print(
            "Skipping test case generation for test ID",
            testCase["ID"],
            "as tesType is RANDOM",
        )


#############################################################################
# Open CSV file with test cases and generate header file with test data for #
# test cases of interest; based on testIdList                               #
#############################################################################

with open(testCasesCsvFile, encoding="utf-8-sig") as csv_file:
    testCaseReader = csv.DictReader(csv_file)
    testCases = list(testCaseReader)

    for testCase in testCases:
        testCase = process_test_case(testCase)

    for testCase in testCases:
        if myArgs.allCases == True:
            gen_test_case(testCase)
        elif int(testCase["ID"]) in testIdList:
            gen_test_case(testCase)


idatFileName = "../../DSPLIB_addNCh/DSPLIB_addNCh_idat.c"


##########################################################################
# Generate idat.cpp file by parsing all the test cases in the CSV file # #
##########################################################################


with open(idatFileName, "w") as idatFile:
    gen_idat_file(idatFile, testCases)


if platform == "linux" or platform == "linux2":
    call(["clang-format", "-style=file", "-i", idatFileName])
    call(["indent", "-nut", "-i3", "-c55", "-l200", idatFileName])
    call(["rm", idatFileName + "~"])  # remove backup file


print("Idat file generation completed")
