# Copyright (C) 2026 Texas Instruments Incorporated
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import print_function
from subprocess import call
from sys import platform

import sys
import numpy as np
import csv
import pandas as pd

sys.path.append("../common")
import DSPLIB_utils
import file_io


def gen_testCaseParams(testParamsFile, currPrm):
    """Generate and write test case parameters to idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    testId = currPrm["ID"]
    dType = currPrm["dType"]
    inSamples = currPrm["inSamples"]
    inChannels = currPrm["inChannels"]
    strideOutElements = currPrm["strideOutElements"]
    constant = currPrm["constant"]
    testType = currPrm["testType"]
    demoCase = currPrm["demoCase"]
    numReps = currPrm["numReps"]
    outputDataLocation = currPrm["outputDataLocation"]

    if testType == "STATIC":
        in1 = "staticRefIn1Case" + testId
        out = "staticRefOutCase" + testId
    else:
        in1 = "NULL"
        out = "NULL"

    if demoCase == "true":
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d) || defined(DEMO_CASE))\n"
            % (int(testId))
        )
    else:
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d))\n" % (int(testId))
        )

    idatFile.write("{\n")
    idatFile.write("%s, // Test pattern \n" % ((testType)))
    idatFile.write("%s, // Input buffer\n" % ((in1)))
    idatFile.write("%s, // Output vector \n" % ((out)))
    idatFile.write("%s, // precision \n" % (DSPLIB_utils.resolve_dType(dType)))
    idatFile.write("%s, // Number of samples in a vector \n" % ((inSamples)))
    idatFile.write("%s, // Number of channels in a vector \n" % ((inChannels)))
    idatFile.write(
        "%s * sizeof(%s), // stride of output buffer \n"
        % ((strideOutElements), (dType))
    )
    idatFile.write("%s, // constant \n" % ((constant)))
    idatFile.write("%s, // Output data location \n" % (outputDataLocation))
    idatFile.write("%d, // number of reps. \n" % (int(numReps)))
    idatFile.write("%d, // test ID\n" % int(testId))
    idatFile.write("},\n")
    idatFile.write("#endif")
    idatFile.write("\n\n")


def gen_idat_file(idatFile, testCases):
    """Generate the idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    fIn = open("../common/ti_lice_header_idat.txt", "r")
    lines = fIn.readlines()
    fIn.close()
    idatFile.writelines(lines)
    includeString = '#include "DSPLIB_blkCopyConst2D_idat.h"'
    idatFile.writelines(includeString)
    idatFile.write("\n")
    idatFile.write("/*This file is autogenerated*/\n")
    idatFile.write("/*Please do not edit*/\n")
    idatFile.write("\n\n")
    # generate ifdefs for header files
    for testCase in testCases:
        if testCase["testType"] == "STATIC":
            DSPLIB_utils.gen_ifdefs(idatFile, testCase)

    # generate parameters for test cases
    idatFile.write("static DSPLIB_blkCopyConst2D_testParams_t testParams[] =  ")
    idatFile.write("{\n")

    for testCase in testCases:
        gen_testCaseParams(idatFile, testCase)

    idatFile.write("};\n\n")
    fIn = open("test_param_function.txt", "r")
    lines = fIn.readlines()

    idatFile.writelines(lines)


def process_test_case(testCase):
    """Convert str to int for necessary parameters

    Args:
        Param1(:obj: dict) : Dictionary object with test case parameters

    Returns:
        Obj: Dictionary object with necessary parameters converted to int

    """

    # print(testCase.keys())
    testCase["testId"] = int(testCase["ID"])
    testCase["inSamples"] = int(testCase["inSamples"])
    testCase["inChannels"] = int(testCase["inChannels"])
    testCase["constant"] = testCase["constant"]

    return testCase


def gen_test_case_header_file(testCase):
    """Generate test case and write out input, filter, and output tensor
    into a header file usable in C/C++ code.

    Args:
        param1 (:obj: dict): A dict object with all the test case
        parameters

    Returns:
        [int int]: Minimum and maximum constant in output feature tensor

    """

    ##############################
    # Get test parameter of case #
    ##############################

    testId = testCase["ID"]
    channels = testCase["inChannels"]
    samples = testCase["inSamples"]
    dType = testCase["dType"]
    constant = testCase["constant"]

    if dType == "int8_t":
        in1 = np.array([constant]).astype("int8")
        out = np.full((channels, samples), constant, dtype="int8")

    elif dType == "uint8_t":
        in1 = np.array([constant]).astype("uint8")
        out = np.full((channels, samples), constant, dtype="uint8")

    elif dType == "int16_t":
        in1 = np.array([constant]).astype("int16")
        out = np.full((channels, samples), constant, dtype="int16")

    elif dType == "uint16_t":
        in1 = np.array([constant]).astype("uint16")
        out = np.full((channels, samples), constant, dtype="uint16")

    elif dType == "int32_t":
        in1 = np.array([constant]).astype("int32")
        out = np.full((channels, samples), constant, dtype="int32")

    elif dType == "uint32_t":
        in1 = np.array([constant]).astype("uint32")
        out = np.full((channels, samples), constant, dtype="uint32")

    elif dType == "int64_t":
        in1 = np.array([constant]).astype("int64")
        out = np.full((channels, samples), constant, dtype="int64")

    elif dType == "uint64_t":
        in1 = np.array([constant]).astype("uint64")
        out = np.full((channels, samples), constant, dtype="uint64")

    elif dType == "float":
        in1 = np.array([constant]).astype("float")
        out = np.full((channels, samples), constant, dtype="float")

    elif dType == "double":
        in1 = np.array([constant]).astype("double")
        out = np.full((channels, samples), constant, dtype="double")

    headerFileName = "staticRefCase" + str(testId) + ".h"

    file_io.write_header_file(in1, out, testCase, headerFileName)

    return [np.min(out), np.max(out)]


# CSV file with paratmeters for all test cases
testCasesCsvFile = "test_cases_list.csv"
df = pd.read_csv(testCasesCsvFile)
num_data_rows = len(df)
testIdList = []  # list of test IDs that we want to generate test data
testIdList += range(1, num_data_rows)


myArgs = DSPLIB_utils.getCmdLineArgs()


def gen_test_case(testCase):
    if testCase["testType"] == "STATIC":
        [minY, maxY] = gen_test_case_header_file(testCase)
        print(
            "Test case generation completed for test ID",
            testCase["ID"],
            "w/ min:",
            minY,
            "and max",
            maxY,
        )
    else:
        print(
            "Skipping test case generation for test ID",
            testCase["ID"],
            "as tesType is RANDOM",
        )


#############################################################################
# Open CSV file with test cases and generate header file with test data for #
# test cases of interest; based on testIdList                               #
#############################################################################

with open(testCasesCsvFile, encoding="utf-8-sig") as csv_file:
    testCaseReader = csv.DictReader(csv_file)
    testCases = list(testCaseReader)

    for testCase in testCases:
        testCase = process_test_case(testCase)

    for testCase in testCases:
        if myArgs.allCases == True:
            gen_test_case(testCase)
        elif int(testCase["ID"]) in testIdList:
            gen_test_case(testCase)


idatFileName = "../../DSPLIB_blkCopyConst2D/DSPLIB_blkCopyConst2D_idat.c"


##########################################################################
# Generate idat.cpp file by parsing all the test cases in the CSV file # #
##########################################################################


with open(idatFileName, "w") as idatFile:
    gen_idat_file(idatFile, testCases)


if platform == "linux" or platform == "linux2":
    call(["clang-format", "-style=file", "-i", idatFileName])
    call(["indent", "-nut", "-i3", "-c55", "-l200", idatFileName])
    call(["rm", idatFileName + "~"])  # remove backup file


print("Idat file generation completed")
