# Copyright (C) 2026 Texas Instruments Incorporated
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import print_function
from subprocess import call
from sys import platform

import sys
import numpy as np
import csv

sys.path.append("../common")
import DSPLIB_utils
import file_io


def gen_testCaseParams(testParamsFile, currPrm):
    """Generate and write test case parameters to idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """
    testType = currPrm["testType"]
    dType = currPrm["dType"]
    widthIn = currPrm["widthIn"]
    heightIn = currPrm["heightIn"]
    strideIn = currPrm["strideIn"]
    widthOut = currPrm["widthOut"]
    heightOut = currPrm["heightOut"]
    strideOut = currPrm["strideOut"]
    demoCase = currPrm["demoCase"]
    outputDataLocation = currPrm["outputDataLocation"]
    numReps = currPrm["numReps"]
    C7100 = currPrm["C7100"]
    testId = currPrm["ID"]
    enableStrideIn = currPrm["enableStrideIn"]

    if testType == "STATIC":
        in0 = "staticRefInCase" + testId
        out = "staticRefOutCase" + testId
    else:
        in0 = "NULL"
        out = "NULL"

    if C7100 == "FALSE":
        testParamsFile.write("#if !defined(__C7100__)\n")

    if demoCase == "true":
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d) || defined(DEMO_CASE))\n"
            % (int(testId))
        )
    else:
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d))\n" % (int(testId))
        )

    idatFile.write("{\n")
    idatFile.write("%s, // testPattern \n" % ((testType)))
    idatFile.write("%s, // *staticIn \n" % ((in0)))
    idatFile.write("%s, // *staticOut\n" % ((out)))
    idatFile.write("%s, // dataType \n" % ((DSPLIB_utils.resolve_dType(dType))))
    idatFile.write("%s, // widthIn \n" % ((widthIn)))
    idatFile.write("%s, // heightIn \n" % ((heightIn)))
    if enableStrideIn == "TRUE":
        idatFile.write(
            "DSPLIB_CALC_STRIDE(%s * sizeof(%s), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn \n"
            % ((strideIn), (dType))
        )
    else:
        idatFile.write("%s, // strideIn \n" % ((strideIn)))
    idatFile.write("%s,  //widthOut \n" % ((widthOut)))
    idatFile.write("%s,  //heightOut\n" % ((heightOut)))
    idatFile.write(
        "DSPLIB_CALC_STRIDE(%s * sizeof(%s), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut \n"
        % ((strideOut), (dType))
    )
    idatFile.write("%s, // Output data location \n" % (outputDataLocation))
    idatFile.write("%d, // number of reps. \n" % (int(numReps)))
    idatFile.write("%d // test ID\n" % int(testId))
    idatFile.write("},\n")
    idatFile.write("#endif\n")

    if C7100 == "FALSE":
        testParamsFile.write("#endif // if !defined(__C7100__)\n")

    idatFile.write("\n\n")


def gen_idat_file(idatFile, testCases):
    """Generate the idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    fIn = open("../common/ti_lice_header_idat.txt", "r")
    lines = fIn.readlines()
    fIn.close()
    idatFile.writelines(lines)
    includeString = '#include "DSPLIB_deinterleave_idat.h"'
    idatFile.writelines(includeString)
    idatFile.write("\n")
    idatFile.write("/*This file is autogenerated*/\n")
    idatFile.write("/*Please do not edit*/\n")
    idatFile.write("\n\n")
    # generate ifdefs for header files
    for testCase in testCases:
        if testCase["testType"] == "STATIC":
            DSPLIB_utils.gen_ifdefs(idatFile, testCase)

    # generate parameters for test cases
    idatFile.write("static DSPLIB_deinterleave_testParams_t testParams[] =  ")
    idatFile.write("{\n")

    for testCase in testCases:
        gen_testCaseParams(idatFile, testCase)

    idatFile.write("};\n\n")
    fIn = open("test_param_function.txt", "r")
    lines = fIn.readlines()

    idatFile.writelines(lines)


def process_test_case(testCase):
    """Convert str to int for necessary parameters

    Args:
        Param1(:obj: dict) : Dictionary object with test case parameters

    Returns:
        Obj: Dictionary object with necessary parameters converted to int

    """

    # print(testCase.keys())
    testCase["testId"] = int(testCase["ID"])
    testCase["widthIn"] = int(testCase["widthIn"])
    testCase["heightIn"] = int(testCase["heightIn"])
    testCase["strideIn"] = int(testCase["strideIn"])
    testCase["strideOut"] = int(testCase["strideOut"])
    testCase["widthOut"] = int(testCase["widthOut"])
    testCase["heightOut"] = int(testCase["heightOut"])
    return testCase


def gen_test_case_header_file(testCase):
    """Generate test case and write out input, filter, and output tensor
    into a header file usable in C/C++ code.

    Args:
        param1 (:obj: dict): A dict object with all the test case
        parameters

    Returns:
        [int int]: Minimum and maximum value in output feature tensor

    """

    ##############################
    # Get test parameter of case #
    ##############################
    testId = testCase["ID"]
    dType = testCase["dType"]
    widthIn = testCase["widthIn"]
    heightIn = testCase["heightIn"]
    widthOut = testCase["widthOut"]
    heightOut = testCase["heightOut"]

    if dType == "int8_t" or dType == "uint8_t":
        bits = 8
    elif dType == "int16_t" or dType == "uint16_t":
        bits = 16
    elif dType == "int32_t" or dType == "uint32_t":
        bits = 32
    else:
        bits = 32

    # unsigned integer
    if dType[0] == "u":
        minVal = 0
        maxVal = (2**bits) - 1
    else:
        minVal = -(2 ** (bits - 1))
        maxVal = 2 ** (bits - 1)

    if dType == "int8_t":
        in0 = np.random.uniform(
            low=minVal, high=maxVal, size=(heightIn, widthIn)
        ).astype("int8")

    elif dType == "int16_t":
        in0 = np.random.uniform(
            low=minVal, high=maxVal, size=(heightIn, widthIn)
        ).astype("int16")

    elif dType == "int32_t":
        in0 = np.random.uniform(
            low=minVal, high=maxVal, size=(heightIn, widthIn)
        ).astype("int32")

    elif dType == "int64_t":
        in0 = np.random.uniform(
            low=minVal, high=maxVal, size=(heightIn, widthIn)
        ).astype("int64")

    elif dType == "uint8_t":
        in0 = np.random.uniform(
            low=minVal, high=maxVal, size=(heightIn, widthIn)
        ).astype("uint8")

    elif dType == "uint16_t":
        in0 = np.random.uniform(
            low=minVal, high=maxVal, size=(heightIn, widthIn)
        ).astype("uint16")

    elif dType == "uint32_t":
        in0 = np.random.uniform(
            low=minVal, high=maxVal, size=(heightIn, widthIn)
        ).astype("uint32")

    elif dType == "uint64_t":
        in0 = np.random.uniform(
            low=minVal, high=maxVal, size=(heightIn, widthIn)
        ).astype("uint64")

    elif dType == "float":
        in0 = np.random.uniform(low=-10, high=10, size=(heightIn, widthIn)).astype(
            "float"
        )

    elif dType == "double":
        in0 = np.random.uniform(low=-10, high=10, size=(heightIn, widthIn)).astype(
            "double"
        )

    out = in0.T
    headerFileName = "staticRefCase" + str(testId) + ".h"
    file_io.write_header_file(in0, out, testCase, headerFileName)

    return [np.min(out), np.max(out)]


# CSV file with paratmeters for all test cases
testCasesCsvFile = "test_cases_list.csv"
testIdList = []  # list of test IDs that we want to generate test data
testIdList += range(0, 200)
# testIdList = [18]

myArgs = DSPLIB_utils.getCmdLineArgs()


def gen_test_case(testCase):
    if testCase["testType"] == "STATIC":
        [minY, maxY] = gen_test_case_header_file(testCase)
        print(
            "Test case generation completed for test ID",
            testCase["ID"],
            "w/ min:",
            minY,
            "and max",
            maxY,
        )
    else:
        print(
            "Skipping test case generation for test ID",
            testCase["ID"],
            "as tesType is RANDOM",
        )


#############################################################################
# Open CSV file with test cases and generate header file with test data for #
# test cases of interest; based on testIdList                               #
#############################################################################

with open(testCasesCsvFile, encoding="utf-8-sig") as csv_file:
    testCaseReader = csv.DictReader(csv_file)
    testCases = list(testCaseReader)

    for testCase in testCases:
        testCase = process_test_case(testCase)

    for testCase in testCases:
        if myArgs.allCases == True:
            gen_test_case(testCase)
        elif int(testCase["ID"]) in testIdList:
            gen_test_case(testCase)


idatFileName = "../../DSPLIB_deinterleave/DSPLIB_deinterleave_idat.c"


##########################################################################
# Generate idat.cpp file by parsing all the test cases in the CSV file # #
##########################################################################


with open(idatFileName, "w") as idatFile:
    gen_idat_file(idatFile, testCases)


if platform == "linux" or platform == "linux2":
    call(["clang-format", "-style=file", "-i", idatFileName])
    call(["indent", "-nut", "-i3", "-c55", "-l200", idatFileName])
    call(["rm", idatFileName + "~"])  # remove backup file


print("Idat file generation completed")
