# Copyright (C) 2026 Texas Instruments Incorporated
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import print_function
from subprocess import call
from sys import platform

import sys
import numpy as np
import csv

sys.path.append("../common")
import pandas as pd
import DSPLIB_utils
import file_io
import os

# sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'common')))


def gen_testCaseParams(testParamsFile, currPrm):
    """Generate and write test case parameters to idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    testId = currPrm["ID"]
    dType = currPrm["dType"]
    inChannels = currPrm["inChannels"]
    inSamples = currPrm["inSamples"]
    strideIn0 = currPrm["strideInElements"]
    strideOut = currPrm["strideOutElements"]
    testType = currPrm["testType"]
    demoCase = currPrm["demoCase"]
    outputDataLocation = currPrm["outputDataLocation"]
    numReps = currPrm["numReps"]
    C7100 = currPrm["C7100"]

    if testType == "STATIC":
        in0 = "staticRefIn0Case" + testId
        in1 = "staticRefIn1Case" + testId
        out = "staticRefOutCase" + testId
    else:
        in0 = "NULL"
        in1 = "NULL"
        out = "NULL"

    if C7100 == "FALSE":
        testParamsFile.write("#if !defined(__C7100__)\n")

    if demoCase == "true":
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d) || defined(DEMO_CASE))\n"
            % (int(testId))
        )
    else:
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d))\n" % (int(testId))
        )

    idatFile.write("{\n")
    idatFile.write("%s, // Test pattern \n" % ((testType)))
    idatFile.write("%s, // Input buffer\n" % ((in0)))
    idatFile.write("%s, // Input realImagToComplex \n" % ((in1)))
    idatFile.write("%s, // Output buffer \n" % ((out)))
    idatFile.write("%s, // inSamples \n" % ((inSamples)))
    idatFile.write("%s, // inChannels \n" % ((inChannels)))
    idatFile.write(
        "DSPLIB_CALC_STRIDE(%s * sizeof(%s), DSPLIB_ALIGN_SHIFT_64BYTES), // strideIn0 \n"
        % ((strideIn0), (dType))
    )
    idatFile.write(
        "DSPLIB_CALC_STRIDE(%s * sizeof(%s), DSPLIB_ALIGN_SHIFT_64BYTES), // strideOut \n"
        % ((strideOut), (dType))
    )
    idatFile.write("%s, // precision \n" % ((DSPLIB_utils.resolve_dType(dType))))
    idatFile.write("%s, // Output data location \n" % (outputDataLocation))
    idatFile.write("%d, // number of reps. \n" % (int(numReps)))
    idatFile.write("%d, // test ID\n" % int(testId))
    idatFile.write("},\n")
    idatFile.write("#endif\n")

    if C7100 == "FALSE":
        testParamsFile.write("#endif // if !defined(__C7100__)\n")

    idatFile.write("\n\n")


def gen_idat_file(idatFile, testCases):
    """Generate the idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    fIn = open("../common/ti_lice_header_idat.txt", "r")
    lines = fIn.readlines()
    fIn.close()
    idatFile.writelines(lines)
    includeString = '#include "DSPLIB_realImagToComplex_idat.h"'
    idatFile.writelines(includeString)
    idatFile.write("\n")
    idatFile.write("/*This file is autogenerated*/\n")
    idatFile.write("/*Please do not edit*/\n")
    idatFile.write("\n\n")
    # generate ifdefs for header files
    for testCase in testCases:
        if testCase["testType"] == "STATIC":
            DSPLIB_utils.gen_ifdefs(idatFile, testCase)

    # generate parameters for test cases
    idatFile.write("static DSPLIB_realImagToComplex_testParams_t testParams[] =  ")
    idatFile.write("{\n")

    for testCase in testCases:
        gen_testCaseParams(idatFile, testCase)

    idatFile.write("};\n\n")
    fIn = open("test_param_function.txt", "r")
    lines = fIn.readlines()

    idatFile.writelines(lines)


def process_test_case(testCase):
    """Convert str to int for necessary parameters

    Args:
        Param1(:obj: dict) : Dictionary object with test case parameters

    Returns:
        Obj: Dictionary object with necessary parameters converted to int

    """

    testCase["testId"] = int(testCase["ID"])
    testCase["inChannels"] = int(testCase["inChannels"])
    testCase["inSamples"] = int(testCase["inSamples"])
    testCase["strideIn0"] = int(testCase["strideInElements"])
    testCase["strideOut"] = int(testCase["strideOutElements"])

    return testCase


def gen_test_case_header_file(testCase):
    """Generate test case and write out input, filter, and output tensor
    into a header file usable in C/C++ code.

    Args:
        param1 (:obj: dict): A dict object with all the test case
        parameters

    Returns:
        [int int]: Minimum and maximum value in output feature tensor

    """

    ##############################
    # Get test parameter of case #
    ##############################

    testId = testCase["ID"]
    dType = testCase["dType"]
    inChannels = testCase["inChannels"]
    inSamples = testCase["inSamples"]

    # [minVal, maxVal] = DSPLIB_utils.minMaxVal(dType)
    [minVal, maxVal] = [-10, 10]

    if dType == "float":
        in0 = np.random.uniform(
            low=minVal, high=maxVal, size=(inChannels, inSamples)
        ).astype("float32")
        in1 = np.random.uniform(
            low=minVal, high=maxVal, size=(inChannels, inSamples)
        ).astype("float32")

    elif dType == "double":
        in0 = np.random.uniform(
            low=minVal, high=maxVal, size=(inChannels, inSamples)
        ).astype("double")
        in1 = np.random.uniform(
            low=minVal, high=maxVal, size=(inChannels, inSamples)
        ).astype("double")

    elif dType == "uint32_t":
        [minVal, maxVal] = [0, 10]

        in0 = np.random.uniform(
            low=minVal, high=maxVal, size=(inChannels, inSamples)
        ).astype("uint32")
        in1 = np.random.uniform(
            low=minVal, high=maxVal, size=(inChannels, inSamples)
        ).astype("uint32")

    elif dType == "int32_t":
        [minVal, maxVal] = [-10, 10]

        in0 = np.random.uniform(
            low=minVal, high=maxVal, size=(inChannels, inSamples)
        ).astype("int32")
        in1 = np.random.uniform(
            low=minVal, high=maxVal, size=(inChannels, inSamples)
        ).astype("int32")

    elif dType == "int16_t":
        [minVal, maxVal] = [-10, 10]

        in0 = np.random.uniform(
            low=minVal, high=maxVal, size=(inChannels, inSamples)
        ).astype("int16")
        in1 = np.random.uniform(
            low=minVal, high=maxVal, size=(inChannels, inSamples)
        ).astype("int16")

    elif dType == "uint16_t":
        [minVal, maxVal] = [0, 10]

        in0 = np.random.uniform(
            low=minVal, high=maxVal, size=(inChannels, inSamples)
        ).astype("uint16")
        in1 = np.random.uniform(
            low=minVal, high=maxVal, size=(inChannels, inSamples)
        ).astype("uint16")

    out = np.empty((inChannels, inSamples * 2), dtype=in0.dtype)
    out[:, 0::2] = in0
    out[:, 1::2] = in1

    headerFileName = "staticRefCase" + str(testId) + ".h"
    file_io.write_header_file(in0, in1, out, testCase, headerFileName)

    return [np.min(out), np.max(out)]


# CSV file with paratmeters for all test cases
testCasesCsvFile = "test_cases_list.csv"
df = pd.read_csv(testCasesCsvFile)
num_data_rows = len(df)
testIdList = []  # list of test IDs that we want to generate test data
testIdList += range(0, num_data_rows + 1)

myArgs = DSPLIB_utils.getCmdLineArgs()


def gen_test_case(testCase):
    if testCase["testType"] == "STATIC":
        [minY, maxY] = gen_test_case_header_file(testCase)
        print(
            "Test case generation completed for test ID",
            testCase["ID"],
            "w/ min:",
            minY,
            "and max",
            maxY,
        )
    else:
        print(
            "Skipping test case generation for test ID",
            testCase["ID"],
            "as tesType is RANDOM",
        )


#############################################################################
# Open CSV file with test cases and generate header file with test data for #
# test cases of interest; based on testIdList                               #
#############################################################################

with open(testCasesCsvFile, encoding="utf-8-sig") as csv_file:
    testCaseReader = csv.DictReader(csv_file)
    testCases = list(testCaseReader)

    for testCase in testCases:
        testCase = process_test_case(testCase)

    for testCase in testCases:
        if myArgs.allCases == True:
            gen_test_case(testCase)
        elif int(testCase["ID"]) in testIdList:
            gen_test_case(testCase)


idatFileName = "../../DSPLIB_realImagToComplex/DSPLIB_realImagToComplex_idat.c"


##########################################################################
# Generate idat.cpp file by parsing all the test cases in the CSV file # #
##########################################################################


with open(idatFileName, "w") as idatFile:
    gen_idat_file(idatFile, testCases)


if platform == "linux" or platform == "linux2":
    call(["clang-format", "-style=file", "-i", idatFileName])
    call(["indent", "-nut", "-i3", "-c55", "-l200", idatFileName])
    call(["rm", idatFileName + "~"])  # remove backup file


print("Idat file generation completed")
